// <auto-generated />
// Generic tri-state wrapper emitted by apigen for properties configured with
// use_generic_optional_type = true. Distinguishes three semantic states:
//   default(Optional<T>)  → Unset (property omitted from JSON output)
//   new Optional<T>(null) → Null  (property serialized as JSON null)
//   new Optional<T>("x")  → Value (property serialized with the value)
//
// Implicit conversion from T means `dto.Prop = "x"`, `dto.Prop = null`, and not
// assigning at all all work without any ritual. To unset after assigning, use
// `dto.Prop = default;`.

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// Generic tri-state wrapper: distinguishes Unset / Null / Value.
/// </summary>
[JsonConverter(typeof(OptionalJsonConverterFactory))]
public readonly struct Optional<T> : IEquatable<Optional<T>>
{
  public Optional(T? value)
  {
    Value = value;
    HasValue = true;
  }

  /// <summary>Underlying value (only meaningful when <see cref="HasValue"/> is true).</summary>
  public T? Value { get; }

  /// <summary>True when this instance represents Null or Value. False for Unset (default).</summary>
  public bool HasValue { get; }

  /// <summary>True when HasValue is true AND Value is null.</summary>
  public bool IsNull => HasValue && Value is null;

  public static implicit operator Optional<T>(T? value) => new Optional<T>(value);
  public static implicit operator T?(Optional<T> optional) => optional.Value;

  public bool Equals(Optional<T> other) =>
    HasValue == other.HasValue && EqualityComparer<T?>.Default.Equals(Value, other.Value);

  public override bool Equals(object? obj) => obj is Optional<T> o && Equals(o);

  public override int GetHashCode() =>
    HasValue ? HashCode.Combine(true, Value) : 0;

  public static bool operator ==(Optional<T> left, Optional<T> right) => left.Equals(right);
  public static bool operator !=(Optional<T> left, Optional<T> right) => !left.Equals(right);
}

/// <summary>
/// JsonConverterFactory that produces per-T converters for <see cref="Optional{T}"/>.
/// </summary>
internal sealed class OptionalJsonConverterFactory : JsonConverterFactory
{
  public override bool CanConvert(Type typeToConvert) =>
    typeToConvert.IsGenericType && typeToConvert.GetGenericTypeDefinition() == typeof(Optional<>);

  public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
  {
    Type innerType = typeToConvert.GetGenericArguments()[0];
    Type converterType = typeof(OptionalJsonConverter<>).MakeGenericType(innerType);
    return (JsonConverter)Activator.CreateInstance(converterType)!;
  }
}

internal sealed class OptionalJsonConverter<T> : JsonConverter<Optional<T>>
{
  public override Optional<T> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
  {
    if (reader.TokenType == JsonTokenType.Null)
    {
      return new Optional<T>(default);
    }
    T? value = JsonSerializer.Deserialize<T>(ref reader, options);
    return new Optional<T>(value);
  }

  public override void Write(Utf8JsonWriter writer, Optional<T> value, JsonSerializerOptions options)
  {
    // When !HasValue the serializer should have skipped this property via
    // [JsonIgnore(WhenWritingDefault)]. If we do get called with an Unset value,
    // fall back to writing JSON null rather than throwing.
    if (value.IsNull || !value.HasValue)
    {
      writer.WriteNullValue();
      return;
    }
    JsonSerializer.Serialize(writer, value.Value, options);
  }
}
