//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// ActivityResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/ActivityResponseDto
/// </summary>
public class ActivityResponseDto
{
  /// <summary>
  /// Asset ID (if activity is for an asset)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assetId")]
  public string? AssetId { get; set; }

  /// <summary>
  /// Comment text (for comment activities)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("comment")]
  public string? Comment { get; set; }

  /// <summary>
  /// Creation date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public DateTime CreatedAt { get; set; }

  /// <summary>
  /// Activity ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Activity type
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public ReactionType Type { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("user")]
  public UserResponseDto User { get; set; } = null!;
}
