//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// ActivityStatisticsResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/ActivityStatisticsResponseDto
/// </summary>
public class ActivityStatisticsResponseDto
{
  /// <summary>
  /// Number of comments
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("comments")]
  public int Comments { get; set; }

  /// <summary>
  /// Number of likes
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("likes")]
  public int Likes { get; set; }
}
