//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// AlbumsAddAssetsResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/AlbumsAddAssetsResponseDto
/// </summary>
public class AlbumsAddAssetsResponseDto
{
  /// <summary>
  /// Error reason
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("error")]
  public BulkIdErrorReason? Error { get; set; }

  /// <summary>
  /// Operation success
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("success")]
  public bool Success { get; set; }
}
