//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// AlbumStatisticsResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/AlbumStatisticsResponseDto
/// </summary>
public class AlbumStatisticsResponseDto
{
  /// <summary>
  /// Number of non-shared albums
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("notShared")]
  public int NotShared { get; set; }

  /// <summary>
  /// Number of owned albums
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("owned")]
  public int Owned { get; set; }

  /// <summary>
  /// Number of shared albums
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("shared")]
  public int Shared { get; set; }
}
