//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// AlbumResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/AlbumResponseDto
/// </summary>
public class AlbumResponseDto
{
  /// <summary>
  /// Album name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("albumName")]
  public string? AlbumName { get; set; }

  /// <summary>
  /// Thumbnail asset ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("albumThumbnailAssetId")]
  public string? AlbumThumbnailAssetId { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("albumUsers")]
  public List<AlbumUserResponseDto>? AlbumUsers { get; set; }

  /// <summary>
  /// Number of assets
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assetCount")]
  public int AssetCount { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assets")]
  public List<AssetResponseDto>? Assets { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("contributorCounts")]
  public List<ContributorCountResponseDto>? ContributorCounts { get; set; }

  /// <summary>
  /// Creation date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public DateTime CreatedAt { get; set; }

  /// <summary>
  /// Album description
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// End date (latest asset)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("endDate")]
  public DateTime? EndDate { get; set; }

  /// <summary>
  /// Has shared link
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("hasSharedLink")]
  public bool HasSharedLink { get; set; }

  /// <summary>
  /// Album ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Activity feed enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isActivityEnabled")]
  public bool IsActivityEnabled { get; set; }

  /// <summary>
  /// Last modified asset timestamp
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("lastModifiedAssetTimestamp")]
  public DateTime? LastModifiedAssetTimestamp { get; set; }

  /// <summary>
  /// Asset sort order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("order")]
  public AssetOrder? Order { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("owner")]
  public UserResponseDto Owner { get; set; } = null!;

  /// <summary>
  /// Owner user ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ownerId")]
  public string? OwnerId { get; set; }

  /// <summary>
  /// Is shared album
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("shared")]
  public bool Shared { get; set; }

  /// <summary>
  /// Start date (earliest asset)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("startDate")]
  public DateTime? StartDate { get; set; }

  /// <summary>
  /// Last update date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
  public DateTime UpdatedAt { get; set; }
}
