//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// AlbumUserAddDto from OpenAPI schema.
/// Schema path: #/components/schemas/AlbumUserAddDto
/// </summary>
public class AlbumUserAddDto
{
  /// <summary>
  /// Album user role
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("role")]
  public AlbumUserRole? Role { get; set; }

  /// <summary>
  /// User ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("userId")]
  public Guid UserId { get; set; }
}
