//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// APIKeyResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/APIKeyResponseDto
/// </summary>
public class ApiKeyResponseDto
{
  /// <summary>
  /// Creation date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public DateTime CreatedAt { get; set; }

  /// <summary>
  /// API key ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// API key name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// List of permissions
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("permissions")]
  public List<Permission>? Permissions { get; set; }

  /// <summary>
  /// Last update date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
  public DateTime UpdatedAt { get; set; }
}
