//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// AssetMediaCreateDto from OpenAPI schema.
/// Schema path: #/components/schemas/AssetMediaCreateDto
/// </summary>
public class AssetMediaCreateDto
{
  /// <summary>
  /// Asset file data
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assetData")]
  public byte[] AssetData { get; set; } = null!;

  /// <summary>
  /// Device asset ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("deviceAssetId")]
  public string? DeviceAssetId { get; set; }

  /// <summary>
  /// Device ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("deviceId")]
  public string? DeviceId { get; set; }

  /// <summary>
  /// Duration (for videos)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("duration")]
  public string? Duration { get; set; }

  /// <summary>
  /// File creation date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("fileCreatedAt")]
  public DateTime FileCreatedAt { get; set; }

  /// <summary>
  /// File modification date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("fileModifiedAt")]
  public DateTime FileModifiedAt { get; set; }

  /// <summary>
  /// Filename
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("filename")]
  public string? Filename { get; set; }

  /// <summary>
  /// Mark as favorite
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isFavorite")]
  public bool? IsFavorite { get; set; }

  /// <summary>
  /// Live photo video ID
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("livePhotoVideoId")]
  public Guid? LivePhotoVideoId { get; set; }

  /// <summary>
  /// Asset metadata items
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("metadata")]
  public List<AssetMetadataUpsertItemDto>? Metadata { get; set; }

  /// <summary>
  /// Sidecar file data
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("sidecarData")]
  public byte[]? SidecarData { get; set; }

  /// <summary>
  /// Asset visibility
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("visibility")]
  public AssetVisibility? Visibility { get; set; }
}
