//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// AssetEditActionItemDto from OpenAPI schema.
/// Schema path: #/components/schemas/AssetEditActionItemDto
/// </summary>
public class AssetEditActionItemDto
{
  /// <summary>
  /// Type of edit action to perform
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("action")]
  public AssetEditAction Action { get; set; }

  /// <summary>
  /// List of edit actions to apply (crop, rotate, or mirror)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("parameters")]
  public object? Parameters { get; set; }
}
