//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// AssetOcrResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/AssetOcrResponseDto
/// </summary>
public class AssetOcrResponseDto
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assetId")]
  public Guid AssetId { get; set; }

  /// <summary>
  /// Confidence score for text detection box
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("boxScore")]
  public double BoxScore { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public Guid Id { get; set; }

  /// <summary>
  /// Recognized text
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("text")]
  public string? Text { get; set; }

  /// <summary>
  /// Confidence score for text recognition
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("textScore")]
  public double TextScore { get; set; }

  /// <summary>
  /// Normalized x coordinate of box corner 1 (0-1)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("x1")]
  public double X1 { get; set; }

  /// <summary>
  /// Normalized x coordinate of box corner 2 (0-1)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("x2")]
  public double X2 { get; set; }

  /// <summary>
  /// Normalized x coordinate of box corner 3 (0-1)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("x3")]
  public double X3 { get; set; }

  /// <summary>
  /// Normalized x coordinate of box corner 4 (0-1)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("x4")]
  public double X4 { get; set; }

  /// <summary>
  /// Normalized y coordinate of box corner 1 (0-1)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("y1")]
  public double Y1 { get; set; }

  /// <summary>
  /// Normalized y coordinate of box corner 2 (0-1)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("y2")]
  public double Y2 { get; set; }

  /// <summary>
  /// Normalized y coordinate of box corner 3 (0-1)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("y3")]
  public double Y3 { get; set; }

  /// <summary>
  /// Normalized y coordinate of box corner 4 (0-1)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("y4")]
  public double Y4 { get; set; }
}
