//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// AssetBulkUploadCheckItem from OpenAPI schema.
/// Schema path: #/components/schemas/AssetBulkUploadCheckItem
/// </summary>
public class AssetBulkUploadCheckItem
{
  /// <summary>
  /// Base64 or hex encoded SHA1 hash
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("checksum")]
  public string? Checksum { get; set; }

  /// <summary>
  /// Asset ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }
}
