//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// AssetCopyDto from OpenAPI schema.
/// Schema path: #/components/schemas/AssetCopyDto
/// </summary>
public class AssetCopyDto
{
  /// <summary>
  /// Copy album associations
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("albums")]
  public bool? Albums { get; set; }

  /// <summary>
  /// Copy favorite status
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("favorite")]
  public bool? Favorite { get; set; }

  /// <summary>
  /// Copy shared links
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("sharedLinks")]
  public bool? SharedLinks { get; set; }

  /// <summary>
  /// Copy sidecar file
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("sidecar")]
  public bool? Sidecar { get; set; }

  /// <summary>
  /// Source asset ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("sourceId")]
  public Guid SourceId { get; set; }

  /// <summary>
  /// Copy stack association
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("stack")]
  public bool? Stack { get; set; }

  /// <summary>
  /// Target asset ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("targetId")]
  public Guid TargetId { get; set; }
}
