//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// AssetStatsResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/AssetStatsResponseDto
/// </summary>
public class AssetStatsResponseDto
{
  /// <summary>
  /// Number of images
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("images")]
  public int Images { get; set; }

  /// <summary>
  /// Total number of assets
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("total")]
  public int Total { get; set; }

  /// <summary>
  /// Number of videos
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("videos")]
  public int Videos { get; set; }
}
