//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// AssetDeltaSyncResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/AssetDeltaSyncResponseDto
/// </summary>
public class AssetDeltaSyncResponseDto
{
  /// <summary>
  /// Deleted asset IDs
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("deleted")]
  public List<string?>? Deleted { get; set; }

  /// <summary>
  /// Whether full sync is needed
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("needsFullSync")]
  public bool NeedsFullSync { get; set; }

  /// <summary>
  /// Upserted assets
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("upserted")]
  public List<AssetResponseDto>? Upserted { get; set; }
}
