//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// AssetResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/AssetResponseDto
/// </summary>
public class AssetResponseDto
{
  /// <summary>
  /// Base64 encoded SHA1 hash
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("checksum")]
  public string? Checksum { get; set; }

  /// <summary>
  /// The UTC timestamp when the asset was originally uploaded to Immich.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public DateTime CreatedAt { get; set; }

  /// <summary>
  /// Device asset ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("deviceAssetId")]
  public string? DeviceAssetId { get; set; }

  /// <summary>
  /// Device ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("deviceId")]
  public string? DeviceId { get; set; }

  /// <summary>
  /// Duplicate group ID
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("duplicateId")]
  public string? DuplicateId { get; set; }

  /// <summary>
  /// Video duration (for videos)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("duration")]
  public string? Duration { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("exifInfo")]
  public ExifResponseDto? ExifInfo { get; set; }

  /// <summary>
  /// The actual UTC timestamp when the file was created/captured, preserving timezone information. This is the authoritative timestamp for chronological sorting within timeline groups. Combined with timezone data, this can be used to determine the exact moment the photo was taken.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("fileCreatedAt")]
  public DateTime FileCreatedAt { get; set; }

  /// <summary>
  /// The UTC timestamp when the file was last modified on the filesystem. This reflects the last time the physical file was changed, which may be different from when the photo was originally taken.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("fileModifiedAt")]
  public DateTime FileModifiedAt { get; set; }

  /// <summary>
  /// Whether asset has metadata
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("hasMetadata")]
  public bool HasMetadata { get; set; }

  /// <summary>
  /// Asset height
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("height")]
  public decimal? Height { get; set; }

  /// <summary>
  /// Asset ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Is archived
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isArchived")]
  public bool IsArchived { get; set; }

  /// <summary>
  /// Is edited
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isEdited")]
  public bool IsEdited { get; set; }

  /// <summary>
  /// Is favorite
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isFavorite")]
  public bool IsFavorite { get; set; }

  /// <summary>
  /// Is offline
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isOffline")]
  public bool IsOffline { get; set; }

  /// <summary>
  /// Is trashed
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isTrashed")]
  public bool IsTrashed { get; set; }

  /// <summary>
  /// Library ID
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("libraryId")]
  public Guid? LibraryId { get; set; }

  /// <summary>
  /// Live photo video ID
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("livePhotoVideoId")]
  public string? LivePhotoVideoId { get; set; }

  /// <summary>
  /// The local date and time when the photo/video was taken, derived from EXIF metadata. This represents the photographer&apos;s local time regardless of timezone, stored as a timezone-agnostic timestamp. Used for timeline grouping by &quot;local&quot; days and months.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("localDateTime")]
  public DateTime LocalDateTime { get; set; }

  /// <summary>
  /// Original file name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("originalFileName")]
  public string? OriginalFileName { get; set; }

  /// <summary>
  /// Original MIME type
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("originalMimeType")]
  public string? OriginalMimeType { get; set; }

  /// <summary>
  /// Original file path
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("originalPath")]
  public string? OriginalPath { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("owner")]
  public UserResponseDto? Owner { get; set; }

  /// <summary>
  /// Owner user ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ownerId")]
  public string? OwnerId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("people")]
  public List<PersonWithFacesResponseDto>? People { get; set; }

  /// <summary>
  /// Is resized
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("resized")]
  public bool? Resized { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("stack")]
  public AssetStackResponseDto? Stack { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("tags")]
  public List<TagResponseDto>? Tags { get; set; }

  /// <summary>
  /// Thumbhash for thumbnail generation (base64) also used as the c query param for thumbnail cache busting.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("thumbhash")]
  public string? Thumbhash { get; set; }

  /// <summary>
  /// Asset type
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public AssetTypeEnum Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("unassignedFaces")]
  public List<AssetFaceWithoutPersonResponseDto>? UnassignedFaces { get; set; }

  /// <summary>
  /// The UTC timestamp when the asset record was last updated in the database. This is automatically maintained by the database and reflects when any field in the asset was last modified.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
  public DateTime UpdatedAt { get; set; }

  /// <summary>
  /// Asset visibility
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("visibility")]
  public AssetVisibility Visibility { get; set; }

  /// <summary>
  /// Asset width
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("width")]
  public decimal? Width { get; set; }
}
