//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// AssetMediaReplaceDto from OpenAPI schema.
/// Schema path: #/components/schemas/AssetMediaReplaceDto
/// </summary>
public class AssetMediaReplaceDto
{
  /// <summary>
  /// Asset file data
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assetData")]
  public byte[] AssetData { get; set; } = null!;

  /// <summary>
  /// Device asset ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("deviceAssetId")]
  public string? DeviceAssetId { get; set; }

  /// <summary>
  /// Device ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("deviceId")]
  public string? DeviceId { get; set; }

  /// <summary>
  /// Duration (for videos)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("duration")]
  public string? Duration { get; set; }

  /// <summary>
  /// File creation date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("fileCreatedAt")]
  public DateTime FileCreatedAt { get; set; }

  /// <summary>
  /// File modification date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("fileModifiedAt")]
  public DateTime FileModifiedAt { get; set; }

  /// <summary>
  /// Filename
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("filename")]
  public string? Filename { get; set; }
}
