//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// AssetBulkUploadCheckResult from OpenAPI schema.
/// Schema path: #/components/schemas/AssetBulkUploadCheckResult
/// </summary>
public class AssetBulkUploadCheckResult
{
  /// <summary>
  /// Upload action
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("action")]
  public string? Action { get; set; }

  /// <summary>
  /// Existing asset ID if duplicate
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("assetId")]
  public string? AssetId { get; set; }

  /// <summary>
  /// Asset ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Whether existing asset is trashed
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isTrashed")]
  public bool? IsTrashed { get; set; }

  /// <summary>
  /// Rejection reason if rejected
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("reason")]
  public string? Reason { get; set; }
}
