//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// AssetFaceCreateDto from OpenAPI schema.
/// Schema path: #/components/schemas/AssetFaceCreateDto
/// </summary>
public class AssetFaceCreateDto
{
  /// <summary>
  /// Asset ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assetId")]
  public Guid AssetId { get; set; }

  /// <summary>
  /// Face bounding box height
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("height")]
  public int Height { get; set; }

  /// <summary>
  /// Image height in pixels
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("imageHeight")]
  public int ImageHeight { get; set; }

  /// <summary>
  /// Image width in pixels
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("imageWidth")]
  public int ImageWidth { get; set; }

  /// <summary>
  /// Person ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("personId")]
  public Guid PersonId { get; set; }

  /// <summary>
  /// Face bounding box width
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("width")]
  public int Width { get; set; }

  /// <summary>
  /// Face bounding box X coordinate
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("x")]
  public int X { get; set; }

  /// <summary>
  /// Face bounding box Y coordinate
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("y")]
  public int Y { get; set; }
}
