//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// AssetFullSyncDto from OpenAPI schema.
/// Schema path: #/components/schemas/AssetFullSyncDto
/// </summary>
public class AssetFullSyncDto
{
  /// <summary>
  /// Last asset ID (pagination)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("lastId")]
  public Guid? LastId { get; set; }

  /// <summary>
  /// Maximum number of assets to return
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("limit")]
  public int Limit { get; set; }

  /// <summary>
  /// Sync assets updated until this date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("updatedUntil")]
  public DateTime UpdatedUntil { get; set; }

  /// <summary>
  /// Filter by user ID
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("userId")]
  public Guid? UserId { get; set; }
}
