//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// AssetBulkUpdateDto from OpenAPI schema.
/// Schema path: #/components/schemas/AssetBulkUpdateDto
/// </summary>
public class AssetBulkUpdateDto
{
  /// <summary>
  /// Original date and time
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("dateTimeOriginal")]
  public string? DateTimeOriginal { get; set; }

  /// <summary>
  /// Relative time offset in seconds
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("dateTimeRelative")]
  public decimal? DateTimeRelative { get; set; }

  /// <summary>
  /// Asset description
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Duplicate ID
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("duplicateId")]
  public string? DuplicateId { get; set; }

  /// <summary>
  /// Asset IDs to update
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ids")]
  public List<Guid>? Ids { get; set; }

  /// <summary>
  /// Mark as favorite
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isFavorite")]
  public bool? IsFavorite { get; set; }

  /// <summary>
  /// Latitude coordinate
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("latitude")]
  public decimal? Latitude { get; set; }

  /// <summary>
  /// Longitude coordinate
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("longitude")]
  public decimal? Longitude { get; set; }

  /// <summary>
  /// Rating in range [1-5], or null for unrated
  /// </summary>
  [Range(-1, 5)]
  [System.Text.Json.Serialization.JsonPropertyName("rating")]
  public decimal? Rating { get; set; }

  /// <summary>
  /// Time zone (IANA timezone)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("timeZone")]
  public string? TimeZone { get; set; }

  /// <summary>
  /// Asset visibility
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("visibility")]
  public AssetVisibility? Visibility { get; set; }
}
