//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// AssetFaceWithoutPersonResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/AssetFaceWithoutPersonResponseDto
/// </summary>
public class AssetFaceWithoutPersonResponseDto
{
  /// <summary>
  /// Bounding box X1 coordinate
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("boundingBoxX1")]
  public int BoundingBoxX1 { get; set; }

  /// <summary>
  /// Bounding box X2 coordinate
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("boundingBoxX2")]
  public int BoundingBoxX2 { get; set; }

  /// <summary>
  /// Bounding box Y1 coordinate
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("boundingBoxY1")]
  public int BoundingBoxY1 { get; set; }

  /// <summary>
  /// Bounding box Y2 coordinate
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("boundingBoxY2")]
  public int BoundingBoxY2 { get; set; }

  /// <summary>
  /// Face ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public Guid Id { get; set; }

  /// <summary>
  /// Image height in pixels
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("imageHeight")]
  public int ImageHeight { get; set; }

  /// <summary>
  /// Image width in pixels
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("imageWidth")]
  public int ImageWidth { get; set; }

  /// <summary>
  /// Face detection source type
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("sourceType")]
  public SourceType? SourceType { get; set; }
}
