//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// AuthStatusResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/AuthStatusResponseDto
/// </summary>
public class AuthStatusResponseDto
{
  /// <summary>
  /// Session expiration date
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("expiresAt")]
  public string? ExpiresAt { get; set; }

  /// <summary>
  /// Is elevated session
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isElevated")]
  public bool IsElevated { get; set; }

  /// <summary>
  /// Has password set
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public bool Password { get; set; }

  /// <summary>
  /// Has PIN code set
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("pinCode")]
  public bool PinCode { get; set; }

  /// <summary>
  /// PIN expiration date
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("pinExpiresAt")]
  public string? PinExpiresAt { get; set; }
}
