//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// BulkIdResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/BulkIdResponseDto
/// </summary>
public class BulkIdResponseDto
{
  /// <summary>
  /// Error reason if failed
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("error")]
  public string? Error { get; set; }

  /// <summary>
  /// ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Whether operation succeeded
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("success")]
  public bool Success { get; set; }
}
