//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// ChangePasswordRequest from OpenAPI schema.
/// Schema path: #/components/schemas/ChangePasswordRequest
/// </summary>
public class ChangePasswordRequest
{
  /// <summary>
  /// Invalidate all other sessions
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("invalidateSessions")]
  public bool? InvalidateSessions { get; set; }

  /// <summary>
  /// New password (min 8 characters)
  /// </summary>
  [Required]
  [MinLength(8)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("newPassword")]
  public string? NewPassword { get; set; }

  /// <summary>
  /// Current password
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }
}
