//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// CheckExistingAssetsDto from OpenAPI schema.
/// Schema path: #/components/schemas/CheckExistingAssetsDto
/// </summary>
public class CheckExistingAssetsDto
{
  /// <summary>
  /// Device asset IDs to check
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("deviceAssetIds")]
  public List<string?>? DeviceAssetIds { get; set; }

  /// <summary>
  /// Device ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("deviceId")]
  public string? DeviceId { get; set; }
}
