//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// ContributorCountResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/ContributorCountResponseDto
/// </summary>
public class ContributorCountResponseDto
{
  /// <summary>
  /// Number of assets contributed
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assetCount")]
  public int AssetCount { get; set; }

  /// <summary>
  /// User ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("userId")]
  public string? UserId { get; set; }
}
