//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// CreateMemoryRequest from OpenAPI schema.
/// Schema path: #/components/schemas/CreateMemoryRequest
/// </summary>
public class CreateMemoryRequest
{
  /// <summary>
  /// Asset IDs to associate with memory
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("assetIds")]
  public List<Guid>? AssetIds { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("data")]
  public required OnThisDayDto Data { get; set; }

  /// <summary>
  /// Date when memory should be hidden
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("hideAt")]
  public DateTime? HideAt { get; set; }

  /// <summary>
  /// Is memory saved
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("isSaved")]
  public bool? IsSaved { get; set; }

  /// <summary>
  /// Memory date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("memoryAt")]
  public DateTime MemoryAt { get; set; }

  /// <summary>
  /// Date when memory was seen
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("seenAt")]
  public DateTime? SeenAt { get; set; }

  /// <summary>
  /// Date when memory should be shown
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("showAt")]
  public DateTime? ShowAt { get; set; }

  /// <summary>
  /// Memory type
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public MemoryType Type { get; set; }
}
