//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// CreateAlbumDto from OpenAPI schema.
/// Schema path: #/components/schemas/CreateAlbumDto
/// </summary>
public class CreateAlbumDto
{
  /// <summary>
  /// Album name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("albumName")]
  public string? AlbumName { get; set; }

  /// <summary>
  /// Album users
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("albumUsers")]
  public List<AlbumUserCreateDto>? AlbumUsers { get; set; }

  /// <summary>
  /// Initial asset IDs
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("assetIds")]
  public List<Guid>? AssetIds { get; set; }

  /// <summary>
  /// Album description
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }
}
