//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// CreateActivityRequest from OpenAPI schema.
/// Schema path: #/components/schemas/CreateActivityRequest
/// </summary>
public class CreateActivityRequest
{
  /// <summary>
  /// Album ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("albumId")]
  public Guid AlbumId { get; set; }

  /// <summary>
  /// Asset ID (if activity is for an asset)
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("assetId")]
  public Guid? AssetId { get; set; }

  /// <summary>
  /// Comment text (required if type is comment)
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("comment")]
  public string? Comment { get; set; }

  /// <summary>
  /// Activity type (like or comment)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public ReactionType Type { get; set; }
}
