//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// CreateSharedLinkRequest from OpenAPI schema.
/// Schema path: #/components/schemas/CreateSharedLinkRequest
/// </summary>
public class CreateSharedLinkRequest
{
  /// <summary>
  /// Album ID (for album sharing)
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("albumId")]
  public Guid? AlbumId { get; set; }

  /// <summary>
  /// Allow downloads
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("allowDownload")]
  public bool? AllowDownload { get; set; }

  /// <summary>
  /// Allow uploads
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("allowUpload")]
  public bool? AllowUpload { get; set; }

  /// <summary>
  /// Asset IDs (for individual assets)
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("assetIds")]
  public List<Guid>? AssetIds { get; set; }

  /// <summary>
  /// Link description
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Expiration date
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("expiresAt")]
  public DateTime? ExpiresAt { get; set; }

  /// <summary>
  /// Link password
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  /// <summary>
  /// Show metadata
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("showMetadata")]
  public bool? ShowMetadata { get; set; }

  /// <summary>
  /// Custom URL slug
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("slug")]
  public string? Slug { get; set; }

  /// <summary>
  /// Shared link type
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public SharedLinkType Type { get; set; }
}
