//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// CropParameters from OpenAPI schema.
/// Schema path: #/components/schemas/CropParameters
/// </summary>
public class CropParameters
{
  /// <summary>
  /// Height of the crop
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("height")]
  public decimal Height { get; set; }

  /// <summary>
  /// Width of the crop
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("width")]
  public decimal Width { get; set; }

  /// <summary>
  /// Top-Left X coordinate of crop
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("x")]
  public decimal X { get; set; }

  /// <summary>
  /// Top-Left Y coordinate of crop
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("y")]
  public decimal Y { get; set; }
}
