//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// DatabaseBackupConfig from OpenAPI schema.
/// Schema path: #/components/schemas/DatabaseBackupConfig
/// </summary>
public class DatabaseBackupConfig
{
  /// <summary>
  /// Cron expression
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("cronExpression")]
  public string? CronExpression { get; set; }

  /// <summary>
  /// Enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool Enabled { get; set; }

  /// <summary>
  /// Keep last amount
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("keepLastAmount")]
  public decimal KeepLastAmount { get; set; }
}
