//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// DownloadArchiveInfo from OpenAPI schema.
/// Schema path: #/components/schemas/DownloadArchiveInfo
/// </summary>
public class DownloadArchiveInfo
{
  /// <summary>
  /// Asset IDs in this archive
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assetIds")]
  public List<string?>? AssetIds { get; set; }

  /// <summary>
  /// Archive size in bytes
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("size")]
  public int Size { get; set; }
}
