//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// DownloadResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/DownloadResponseDto
/// </summary>
public class DownloadResponseDto
{
  /// <summary>
  /// Archive information
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("archives")]
  public List<DownloadArchiveInfo>? Archives { get; set; }

  /// <summary>
  /// Total size in bytes
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("totalSize")]
  public int TotalSize { get; set; }
}
