//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// DownloadUpdate from OpenAPI schema.
/// Schema path: #/components/schemas/DownloadUpdate
/// </summary>
public class DownloadUpdate
{
  /// <summary>
  /// Maximum archive size in bytes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("archiveSize")]
  public int? ArchiveSize { get; set; }

  /// <summary>
  /// Whether to include embedded videos in downloads
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("includeEmbeddedVideos")]
  public bool? IncludeEmbeddedVideos { get; set; }
}
