//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// DownloadArchiveDto from OpenAPI schema.
/// Schema path: #/components/schemas/DownloadArchiveDto
/// </summary>
public class DownloadArchiveDto
{
  /// <summary>
  /// Asset IDs
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assetIds")]
  public List<Guid>? AssetIds { get; set; }

  /// <summary>
  /// Download edited asset if available
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("edited")]
  public bool? Edited { get; set; }
}
