//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// DuplicateDetectionConfig from OpenAPI schema.
/// Schema path: #/components/schemas/DuplicateDetectionConfig
/// </summary>
public class DuplicateDetectionConfig
{
  /// <summary>
  /// Whether the task is enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool Enabled { get; set; }

  /// <summary>
  /// Maximum distance threshold for duplicate detection
  /// </summary>
  [Required]
  [Range(0.001, 0.1)]
  [System.Text.Json.Serialization.JsonPropertyName("maxDistance")]
  public double MaxDistance { get; set; }
}
