//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// EmailNotificationsResponse from OpenAPI schema.
/// Schema path: #/components/schemas/EmailNotificationsResponse
/// </summary>
public class EmailNotificationsResponse
{
  /// <summary>
  /// Whether to receive email notifications for album invites
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("albumInvite")]
  public bool AlbumInvite { get; set; }

  /// <summary>
  /// Whether to receive email notifications for album updates
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("albumUpdate")]
  public bool AlbumUpdate { get; set; }

  /// <summary>
  /// Whether email notifications are enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool Enabled { get; set; }
}
