//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// ExifResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/ExifResponseDto
/// </summary>
public class ExifResponseDto
{
  /// <summary>
  /// City name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("city")]
  public string? City { get; set; }

  /// <summary>
  /// Country name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("country")]
  public string? Country { get; set; }

  /// <summary>
  /// Original date/time
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("dateTimeOriginal")]
  public DateTime? DateTimeOriginal { get; set; }

  /// <summary>
  /// Image description
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Image height in pixels
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("exifImageHeight")]
  public decimal? ExifImageHeight { get; set; }

  /// <summary>
  /// Image width in pixels
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("exifImageWidth")]
  public decimal? ExifImageWidth { get; set; }

  /// <summary>
  /// Exposure time
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("exposureTime")]
  public string? ExposureTime { get; set; }

  /// <summary>
  /// F-number (aperture)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("fNumber")]
  public decimal? FNumber { get; set; }

  /// <summary>
  /// File size in bytes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("fileSizeInByte")]
  public long? FileSizeInByte { get; set; }

  /// <summary>
  /// Focal length in mm
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("focalLength")]
  public decimal? FocalLength { get; set; }

  /// <summary>
  /// ISO sensitivity
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("iso")]
  public decimal? Iso { get; set; }

  /// <summary>
  /// GPS latitude
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("latitude")]
  public decimal? Latitude { get; set; }

  /// <summary>
  /// Lens model
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("lensModel")]
  public string? LensModel { get; set; }

  /// <summary>
  /// GPS longitude
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("longitude")]
  public decimal? Longitude { get; set; }

  /// <summary>
  /// Camera make
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("make")]
  public string? Make { get; set; }

  /// <summary>
  /// Camera model
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("model")]
  public string? Model { get; set; }

  /// <summary>
  /// Modification date/time
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("modifyDate")]
  public DateTime? ModifyDate { get; set; }

  /// <summary>
  /// Image orientation
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("orientation")]
  public string? Orientation { get; set; }

  /// <summary>
  /// Projection type
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("projectionType")]
  public string? ProjectionType { get; set; }

  /// <summary>
  /// Rating
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("rating")]
  public decimal? Rating { get; set; }

  /// <summary>
  /// State/province name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("state")]
  public string? State { get; set; }

  /// <summary>
  /// Time zone
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("timeZone")]
  public string? TimeZone { get; set; }
}
