//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// FacialRecognitionConfig from OpenAPI schema.
/// Schema path: #/components/schemas/FacialRecognitionConfig
/// </summary>
public class FacialRecognitionConfig
{
  /// <summary>
  /// Whether the task is enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool Enabled { get; set; }

  /// <summary>
  /// Maximum distance threshold for face recognition
  /// </summary>
  [Required]
  [Range(0.1, 2)]
  [System.Text.Json.Serialization.JsonPropertyName("maxDistance")]
  public double MaxDistance { get; set; }

  /// <summary>
  /// Minimum number of faces required for recognition
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("minFaces")]
  public int MinFaces { get; set; }

  /// <summary>
  /// Minimum confidence score for face detection
  /// </summary>
  [Required]
  [Range(0.1, 1)]
  [System.Text.Json.Serialization.JsonPropertyName("minScore")]
  public double MinScore { get; set; }

  /// <summary>
  /// Name of the model to use
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("modelName")]
  public string? ModelName { get; set; }
}
