//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// FoldersUpdate from OpenAPI schema.
/// Schema path: #/components/schemas/FoldersUpdate
/// </summary>
public class FoldersUpdate
{
  /// <summary>
  /// Whether folders are enabled
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool? Enabled { get; set; }

  /// <summary>
  /// Whether folders appear in web sidebar
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("sidebarWeb")]
  public bool? SidebarWeb { get; set; }
}
