using System;
using System.Text.Json.Serialization;

namespace Apigen.Immich.Models;

/// <summary>
/// Job name
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum JobName
{
    [JsonStringEnumMemberName("AssetDelete")]
    AssetDelete,
    [JsonStringEnumMemberName("AssetDeleteCheck")]
    AssetDeleteCheck,
    [JsonStringEnumMemberName("AssetDetectFacesQueueAll")]
    AssetDetectFacesQueueAll,
    [JsonStringEnumMemberName("AssetDetectFaces")]
    AssetDetectFaces,
    [JsonStringEnumMemberName("AssetDetectDuplicatesQueueAll")]
    AssetDetectDuplicatesQueueAll,
    [JsonStringEnumMemberName("AssetDetectDuplicates")]
    AssetDetectDuplicates,
    [JsonStringEnumMemberName("AssetEditThumbnailGeneration")]
    AssetEditThumbnailGeneration,
    [JsonStringEnumMemberName("AssetEncodeVideoQueueAll")]
    AssetEncodeVideoQueueAll,
    [JsonStringEnumMemberName("AssetEncodeVideo")]
    AssetEncodeVideo,
    [JsonStringEnumMemberName("AssetEmptyTrash")]
    AssetEmptyTrash,
    [JsonStringEnumMemberName("AssetExtractMetadataQueueAll")]
    AssetExtractMetadataQueueAll,
    [JsonStringEnumMemberName("AssetExtractMetadata")]
    AssetExtractMetadata,
    [JsonStringEnumMemberName("AssetFileMigration")]
    AssetFileMigration,
    [JsonStringEnumMemberName("AssetGenerateThumbnailsQueueAll")]
    AssetGenerateThumbnailsQueueAll,
    [JsonStringEnumMemberName("AssetGenerateThumbnails")]
    AssetGenerateThumbnails,
    [JsonStringEnumMemberName("AuditLogCleanup")]
    AuditLogCleanup,
    [JsonStringEnumMemberName("AuditTableCleanup")]
    AuditTableCleanup,
    [JsonStringEnumMemberName("DatabaseBackup")]
    DatabaseBackup,
    [JsonStringEnumMemberName("FacialRecognitionQueueAll")]
    FacialRecognitionQueueAll,
    [JsonStringEnumMemberName("FacialRecognition")]
    FacialRecognition,
    [JsonStringEnumMemberName("FileDelete")]
    FileDelete,
    [JsonStringEnumMemberName("FileMigrationQueueAll")]
    FileMigrationQueueAll,
    [JsonStringEnumMemberName("LibraryDeleteCheck")]
    LibraryDeleteCheck,
    [JsonStringEnumMemberName("LibraryDelete")]
    LibraryDelete,
    [JsonStringEnumMemberName("LibraryRemoveAsset")]
    LibraryRemoveAsset,
    [JsonStringEnumMemberName("LibraryScanAssetsQueueAll")]
    LibraryScanAssetsQueueAll,
    [JsonStringEnumMemberName("LibrarySyncAssets")]
    LibrarySyncAssets,
    [JsonStringEnumMemberName("LibrarySyncFilesQueueAll")]
    LibrarySyncFilesQueueAll,
    [JsonStringEnumMemberName("LibrarySyncFiles")]
    LibrarySyncFiles,
    [JsonStringEnumMemberName("LibraryScanQueueAll")]
    LibraryScanQueueAll,
    [JsonStringEnumMemberName("MemoryCleanup")]
    MemoryCleanup,
    [JsonStringEnumMemberName("MemoryGenerate")]
    MemoryGenerate,
    [JsonStringEnumMemberName("NotificationsCleanup")]
    NotificationsCleanup,
    [JsonStringEnumMemberName("NotifyUserSignup")]
    NotifyUserSignup,
    [JsonStringEnumMemberName("NotifyAlbumInvite")]
    NotifyAlbumInvite,
    [JsonStringEnumMemberName("NotifyAlbumUpdate")]
    NotifyAlbumUpdate,
    [JsonStringEnumMemberName("UserDelete")]
    UserDelete,
    [JsonStringEnumMemberName("UserDeleteCheck")]
    UserDeleteCheck,
    [JsonStringEnumMemberName("UserSyncUsage")]
    UserSyncUsage,
    [JsonStringEnumMemberName("PersonCleanup")]
    PersonCleanup,
    [JsonStringEnumMemberName("PersonFileMigration")]
    PersonFileMigration,
    [JsonStringEnumMemberName("PersonGenerateThumbnail")]
    PersonGenerateThumbnail,
    [JsonStringEnumMemberName("SessionCleanup")]
    SessionCleanup,
    [JsonStringEnumMemberName("SendMail")]
    SendMail,
    [JsonStringEnumMemberName("SidecarQueueAll")]
    SidecarQueueAll,
    [JsonStringEnumMemberName("SidecarCheck")]
    SidecarCheck,
    [JsonStringEnumMemberName("SidecarWrite")]
    SidecarWrite,
    [JsonStringEnumMemberName("SmartSearchQueueAll")]
    SmartSearchQueueAll,
    [JsonStringEnumMemberName("SmartSearch")]
    SmartSearch,
    [JsonStringEnumMemberName("StorageTemplateMigration")]
    StorageTemplateMigration,
    [JsonStringEnumMemberName("StorageTemplateMigrationSingle")]
    StorageTemplateMigrationSingle,
    [JsonStringEnumMemberName("TagCleanup")]
    TagCleanup,
    [JsonStringEnumMemberName("VersionCheck")]
    VersionCheck,
    [JsonStringEnumMemberName("OcrQueueAll")]
    OcrQueueAll,
    [JsonStringEnumMemberName("Ocr")]
    Ocr,
    [JsonStringEnumMemberName("WorkflowRun")]
    WorkflowRun,
}
