//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// LibraryResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/LibraryResponseDto
/// </summary>
public class LibraryResponseDto
{
  /// <summary>
  /// Number of assets
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assetCount")]
  public int AssetCount { get; set; }

  /// <summary>
  /// Creation date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public DateTime CreatedAt { get; set; }

  /// <summary>
  /// Exclusion patterns
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("exclusionPatterns")]
  public List<string?>? ExclusionPatterns { get; set; }

  /// <summary>
  /// Library ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Import paths
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("importPaths")]
  public List<string?>? ImportPaths { get; set; }

  /// <summary>
  /// Library name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// Owner user ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ownerId")]
  public string? OwnerId { get; set; }

  /// <summary>
  /// Last refresh date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("refreshedAt")]
  public DateTime? RefreshedAt { get; set; }

  /// <summary>
  /// Last update date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
  public DateTime UpdatedAt { get; set; }
}
