//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// LibraryStatsResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/LibraryStatsResponseDto
/// </summary>
public class LibraryStatsResponseDto
{
  /// <summary>
  /// Number of photos
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("photos")]
  public int Photos { get; set; }

  /// <summary>
  /// Total number of assets
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("total")]
  public int Total { get; set; }

  /// <summary>
  /// Storage usage in bytes
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("usage")]
  public long Usage { get; set; }

  /// <summary>
  /// Number of videos
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("videos")]
  public int Videos { get; set; }
}
