//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// LicenseResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/LicenseResponseDto
/// </summary>
public class LicenseResponseDto
{
  /// <summary>
  /// Activation date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("activatedAt")]
  public DateTime ActivatedAt { get; set; }

  /// <summary>
  /// Activation key
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("activationKey")]
  public string? ActivationKey { get; set; }

  /// <summary>
  /// License key (format: IM(SV|CL)(-XXXX){8})
  /// </summary>
  [Required]
  [RegularExpression(@"/IM(SV|CL)(-[\dA-Za-z]{4}){8}/")]
  [System.Text.Json.Serialization.JsonPropertyName("licenseKey")]
  public string? LicenseKey { get; set; }
}
