//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// LoginResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/LoginResponseDto
/// </summary>
public class LoginResponseDto
{
  /// <summary>
  /// Access token
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("accessToken")]
  public string? AccessToken { get; set; }

  /// <summary>
  /// Is admin user
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isAdmin")]
  public bool IsAdmin { get; set; }

  /// <summary>
  /// Is onboarded
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isOnboarded")]
  public bool IsOnboarded { get; set; }

  /// <summary>
  /// User name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// Profile image path
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("profileImagePath")]
  public string? ProfileImagePath { get; set; }

  /// <summary>
  /// Should change password
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("shouldChangePassword")]
  public bool ShouldChangePassword { get; set; }

  /// <summary>
  /// User email
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("userEmail")]
  public string? UserEmail { get; set; }

  /// <summary>
  /// User ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("userId")]
  public string? UserId { get; set; }
}
