//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// MachineLearningAvailabilityChecksDto from OpenAPI schema.
/// Schema path: #/components/schemas/MachineLearningAvailabilityChecksDto
/// </summary>
public class MachineLearningAvailabilityChecksDto
{
  /// <summary>
  /// Enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool Enabled { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("interval")]
  public decimal Interval { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("timeout")]
  public decimal Timeout { get; set; }
}
