//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// MaintenanceDetectInstallStorageFolderDto from OpenAPI schema.
/// Schema path: #/components/schemas/MaintenanceDetectInstallStorageFolderDto
/// </summary>
public class MaintenanceDetectInstallStorageFolderDto
{
  /// <summary>
  /// Number of files in the folder
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("files")]
  public decimal Files { get; set; }

  /// <summary>
  /// Storage folder
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("folder")]
  public StorageFolder Folder { get; set; }

  /// <summary>
  /// Whether the folder is readable
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("readable")]
  public bool Readable { get; set; }

  /// <summary>
  /// Whether the folder is writable
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("writable")]
  public bool Writable { get; set; }
}
