//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// MaintenanceStatusResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/MaintenanceStatusResponseDto
/// </summary>
public class MaintenanceStatusResponseDto
{
  /// <summary>
  /// Maintenance action
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("action")]
  public MaintenanceAction Action { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("active")]
  public bool Active { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("error")]
  public string? Error { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("progress")]
  public decimal? Progress { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("task")]
  public string? Task { get; set; }
}
