//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// MapMarkerResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/MapMarkerResponseDto
/// </summary>
public class MapMarkerResponseDto
{
  /// <summary>
  /// City name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("city")]
  public string? City { get; set; }

  /// <summary>
  /// Country name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("country")]
  public string? Country { get; set; }

  /// <summary>
  /// Asset ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Latitude
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("lat")]
  public double Lat { get; set; }

  /// <summary>
  /// Longitude
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("lon")]
  public double Lon { get; set; }

  /// <summary>
  /// State/Province name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("state")]
  public string? State { get; set; }
}
