//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// MemoryUpdateDto from OpenAPI schema.
/// Schema path: #/components/schemas/MemoryUpdateDto
/// </summary>
public class MemoryUpdateDto
{
  /// <summary>
  /// Is memory saved
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isSaved")]
  public bool? IsSaved { get; set; }

  /// <summary>
  /// Memory date
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("memoryAt")]
  public DateTime? MemoryAt { get; set; }

  /// <summary>
  /// Date when memory was seen
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("seenAt")]
  public DateTime? SeenAt { get; set; }
}
