//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// MemoryResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/MemoryResponseDto
/// </summary>
public class MemoryResponseDto
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assets")]
  public List<AssetResponseDto>? Assets { get; set; }

  /// <summary>
  /// Creation date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public DateTime CreatedAt { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("data")]
  public OnThisDayDto Data { get; set; } = null!;

  /// <summary>
  /// Deletion date
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("deletedAt")]
  public DateTime? DeletedAt { get; set; }

  /// <summary>
  /// Date when memory should be hidden
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("hideAt")]
  public DateTime? HideAt { get; set; }

  /// <summary>
  /// Memory ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Is memory saved
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isSaved")]
  public bool IsSaved { get; set; }

  /// <summary>
  /// Memory date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("memoryAt")]
  public DateTime MemoryAt { get; set; }

  /// <summary>
  /// Owner user ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ownerId")]
  public string? OwnerId { get; set; }

  /// <summary>
  /// Date when memory was seen
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("seenAt")]
  public DateTime? SeenAt { get; set; }

  /// <summary>
  /// Date when memory should be shown
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("showAt")]
  public DateTime? ShowAt { get; set; }

  /// <summary>
  /// Memory type
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public MemoryType Type { get; set; }

  /// <summary>
  /// Last update date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
  public DateTime UpdatedAt { get; set; }
}
