//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// NotificationCreateDto from OpenAPI schema.
/// Schema path: #/components/schemas/NotificationCreateDto
/// </summary>
public class NotificationCreateDto
{
  /// <summary>
  /// Additional notification data
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("data")]
  public object? Data { get; set; }

  /// <summary>
  /// Notification description
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Notification level
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("level")]
  public NotificationLevel? Level { get; set; }

  /// <summary>
  /// Date when notification was read
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("readAt")]
  public DateTime? ReadAt { get; set; }

  /// <summary>
  /// Notification title
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }

  /// <summary>
  /// Notification type
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public NotificationType? Type { get; set; }

  /// <summary>
  /// User ID to send notification to
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("userId")]
  public Guid UserId { get; set; }
}
