//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// OAuthCallbackDto from OpenAPI schema.
/// Schema path: #/components/schemas/OAuthCallbackDto
/// </summary>
public class OAuthCallbackDto
{
  /// <summary>
  /// OAuth code verifier (PKCE)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("codeVerifier")]
  public string? CodeVerifier { get; set; }

  /// <summary>
  /// OAuth state parameter
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("state")]
  public string? State { get; set; }

  /// <summary>
  /// OAuth callback URL
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("url")]
  public string? Url { get; set; }
}
