//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// OcrConfig from OpenAPI schema.
/// Schema path: #/components/schemas/OcrConfig
/// </summary>
public class OcrConfig
{
  /// <summary>
  /// Whether the task is enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool Enabled { get; set; }

  /// <summary>
  /// Maximum resolution for OCR processing
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("maxResolution")]
  public int MaxResolution { get; set; }

  /// <summary>
  /// Minimum confidence score for text detection
  /// </summary>
  [Required]
  [Range(0.1, 1)]
  [System.Text.Json.Serialization.JsonPropertyName("minDetectionScore")]
  public double MinDetectionScore { get; set; }

  /// <summary>
  /// Minimum confidence score for text recognition
  /// </summary>
  [Required]
  [Range(0.1, 1)]
  [System.Text.Json.Serialization.JsonPropertyName("minRecognitionScore")]
  public double MinRecognitionScore { get; set; }

  /// <summary>
  /// Name of the model to use
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("modelName")]
  public string? ModelName { get; set; }
}
