//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// PartnerResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/PartnerResponseDto
/// </summary>
public class PartnerResponseDto
{
  /// <summary>
  /// Avatar color
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("avatarColor")]
  public UserAvatarColor AvatarColor { get; set; }

  /// <summary>
  /// User email
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  /// <summary>
  /// User ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Show in timeline
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("inTimeline")]
  public bool? InTimeline { get; set; }

  /// <summary>
  /// User name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// Profile change date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("profileChangedAt")]
  public DateTime ProfileChangedAt { get; set; }

  /// <summary>
  /// Profile image path
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("profileImagePath")]
  public string? ProfileImagePath { get; set; }
}
