//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// PeopleUpdateItem from OpenAPI schema.
/// Schema path: #/components/schemas/PeopleUpdateItem
/// </summary>
public class PeopleUpdateItem
{
  /// <summary>
  /// Person date of birth
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("birthDate")]
  public DateOnly? BirthDate { get; set; }

  /// <summary>
  /// Person color (hex)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("color")]
  public string? Color { get; set; }

  /// <summary>
  /// Asset ID used for feature face thumbnail
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("featureFaceAssetId")]
  public Guid? FeatureFaceAssetId { get; set; }

  /// <summary>
  /// Person ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Mark as favorite
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isFavorite")]
  public bool? IsFavorite { get; set; }

  /// <summary>
  /// Person visibility (hidden)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isHidden")]
  public bool? IsHidden { get; set; }

  /// <summary>
  /// Person name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }
}
