//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// PeopleResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/PeopleResponseDto
/// </summary>
public class PeopleResponseDto
{
  /// <summary>
  /// Whether there are more pages
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("hasNextPage")]
  public bool? HasNextPage { get; set; }

  /// <summary>
  /// Number of hidden people
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("hidden")]
  public int Hidden { get; set; }

  /// <summary>
  /// List of people
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("people")]
  public List<PersonResponseDto>? People { get; set; }

  /// <summary>
  /// Total number of people
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("total")]
  public int Total { get; set; }
}
