using System;
using System.Text.Json.Serialization;

namespace Apigen.Immich.Models;

/// <summary>
/// List of permissions
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum Permission
{
    [JsonStringEnumMemberName("all")]
    All,
    [JsonStringEnumMemberName("activity.create")]
    ActivityDotcreate,
    [JsonStringEnumMemberName("activity.read")]
    ActivityDotread,
    [JsonStringEnumMemberName("activity.update")]
    ActivityDotupdate,
    [JsonStringEnumMemberName("activity.delete")]
    ActivityDotdelete,
    [JsonStringEnumMemberName("activity.statistics")]
    ActivityDotstatistics,
    [JsonStringEnumMemberName("apiKey.create")]
    ApiKeyDotcreate,
    [JsonStringEnumMemberName("apiKey.read")]
    ApiKeyDotread,
    [JsonStringEnumMemberName("apiKey.update")]
    ApiKeyDotupdate,
    [JsonStringEnumMemberName("apiKey.delete")]
    ApiKeyDotdelete,
    [JsonStringEnumMemberName("asset.read")]
    AssetDotread,
    [JsonStringEnumMemberName("asset.update")]
    AssetDotupdate,
    [JsonStringEnumMemberName("asset.delete")]
    AssetDotdelete,
    [JsonStringEnumMemberName("asset.statistics")]
    AssetDotstatistics,
    [JsonStringEnumMemberName("asset.share")]
    AssetDotshare,
    [JsonStringEnumMemberName("asset.view")]
    AssetDotview,
    [JsonStringEnumMemberName("asset.download")]
    AssetDotdownload,
    [JsonStringEnumMemberName("asset.upload")]
    AssetDotupload,
    [JsonStringEnumMemberName("asset.replace")]
    AssetDotreplace,
    [JsonStringEnumMemberName("asset.copy")]
    AssetDotcopy,
    [JsonStringEnumMemberName("asset.derive")]
    AssetDotderive,
    [JsonStringEnumMemberName("asset.edit.get")]
    AssetDoteditDotget,
    [JsonStringEnumMemberName("asset.edit.create")]
    AssetDoteditDotcreate,
    [JsonStringEnumMemberName("asset.edit.delete")]
    AssetDoteditDotdelete,
    [JsonStringEnumMemberName("album.create")]
    AlbumDotcreate,
    [JsonStringEnumMemberName("album.read")]
    AlbumDotread,
    [JsonStringEnumMemberName("album.update")]
    AlbumDotupdate,
    [JsonStringEnumMemberName("album.delete")]
    AlbumDotdelete,
    [JsonStringEnumMemberName("album.statistics")]
    AlbumDotstatistics,
    [JsonStringEnumMemberName("album.share")]
    AlbumDotshare,
    [JsonStringEnumMemberName("album.download")]
    AlbumDotdownload,
    [JsonStringEnumMemberName("albumAsset.create")]
    AlbumAssetDotcreate,
    [JsonStringEnumMemberName("albumAsset.delete")]
    AlbumAssetDotdelete,
    [JsonStringEnumMemberName("albumUser.create")]
    AlbumUserDotcreate,
    [JsonStringEnumMemberName("albumUser.update")]
    AlbumUserDotupdate,
    [JsonStringEnumMemberName("albumUser.delete")]
    AlbumUserDotdelete,
    [JsonStringEnumMemberName("auth.changePassword")]
    AuthDotchangePassword,
    [JsonStringEnumMemberName("authDevice.delete")]
    AuthDeviceDotdelete,
    [JsonStringEnumMemberName("archive.read")]
    ArchiveDotread,
    [JsonStringEnumMemberName("backup.list")]
    BackupDotlist,
    [JsonStringEnumMemberName("backup.download")]
    BackupDotdownload,
    [JsonStringEnumMemberName("backup.upload")]
    BackupDotupload,
    [JsonStringEnumMemberName("backup.delete")]
    BackupDotdelete,
    [JsonStringEnumMemberName("duplicate.read")]
    DuplicateDotread,
    [JsonStringEnumMemberName("duplicate.delete")]
    DuplicateDotdelete,
    [JsonStringEnumMemberName("face.create")]
    FaceDotcreate,
    [JsonStringEnumMemberName("face.read")]
    FaceDotread,
    [JsonStringEnumMemberName("face.update")]
    FaceDotupdate,
    [JsonStringEnumMemberName("face.delete")]
    FaceDotdelete,
    [JsonStringEnumMemberName("folder.read")]
    FolderDotread,
    [JsonStringEnumMemberName("job.create")]
    JobDotcreate,
    [JsonStringEnumMemberName("job.read")]
    JobDotread,
    [JsonStringEnumMemberName("library.create")]
    LibraryDotcreate,
    [JsonStringEnumMemberName("library.read")]
    LibraryDotread,
    [JsonStringEnumMemberName("library.update")]
    LibraryDotupdate,
    [JsonStringEnumMemberName("library.delete")]
    LibraryDotdelete,
    [JsonStringEnumMemberName("library.statistics")]
    LibraryDotstatistics,
    [JsonStringEnumMemberName("timeline.read")]
    TimelineDotread,
    [JsonStringEnumMemberName("timeline.download")]
    TimelineDotdownload,
    [JsonStringEnumMemberName("maintenance")]
    Maintenance,
    [JsonStringEnumMemberName("map.read")]
    MapDotread,
    [JsonStringEnumMemberName("map.search")]
    MapDotsearch,
    [JsonStringEnumMemberName("memory.create")]
    MemoryDotcreate,
    [JsonStringEnumMemberName("memory.read")]
    MemoryDotread,
    [JsonStringEnumMemberName("memory.update")]
    MemoryDotupdate,
    [JsonStringEnumMemberName("memory.delete")]
    MemoryDotdelete,
    [JsonStringEnumMemberName("memory.statistics")]
    MemoryDotstatistics,
    [JsonStringEnumMemberName("memoryAsset.create")]
    MemoryAssetDotcreate,
    [JsonStringEnumMemberName("memoryAsset.delete")]
    MemoryAssetDotdelete,
    [JsonStringEnumMemberName("notification.create")]
    NotificationDotcreate,
    [JsonStringEnumMemberName("notification.read")]
    NotificationDotread,
    [JsonStringEnumMemberName("notification.update")]
    NotificationDotupdate,
    [JsonStringEnumMemberName("notification.delete")]
    NotificationDotdelete,
    [JsonStringEnumMemberName("partner.create")]
    PartnerDotcreate,
    [JsonStringEnumMemberName("partner.read")]
    PartnerDotread,
    [JsonStringEnumMemberName("partner.update")]
    PartnerDotupdate,
    [JsonStringEnumMemberName("partner.delete")]
    PartnerDotdelete,
    [JsonStringEnumMemberName("person.create")]
    PersonDotcreate,
    [JsonStringEnumMemberName("person.read")]
    PersonDotread,
    [JsonStringEnumMemberName("person.update")]
    PersonDotupdate,
    [JsonStringEnumMemberName("person.delete")]
    PersonDotdelete,
    [JsonStringEnumMemberName("person.statistics")]
    PersonDotstatistics,
    [JsonStringEnumMemberName("person.merge")]
    PersonDotmerge,
    [JsonStringEnumMemberName("person.reassign")]
    PersonDotreassign,
    [JsonStringEnumMemberName("pinCode.create")]
    PinCodeDotcreate,
    [JsonStringEnumMemberName("pinCode.update")]
    PinCodeDotupdate,
    [JsonStringEnumMemberName("pinCode.delete")]
    PinCodeDotdelete,
    [JsonStringEnumMemberName("plugin.create")]
    PluginDotcreate,
    [JsonStringEnumMemberName("plugin.read")]
    PluginDotread,
    [JsonStringEnumMemberName("plugin.update")]
    PluginDotupdate,
    [JsonStringEnumMemberName("plugin.delete")]
    PluginDotdelete,
    [JsonStringEnumMemberName("server.about")]
    ServerDotabout,
    [JsonStringEnumMemberName("server.apkLinks")]
    ServerDotapkLinks,
    [JsonStringEnumMemberName("server.storage")]
    ServerDotstorage,
    [JsonStringEnumMemberName("server.statistics")]
    ServerDotstatistics,
    [JsonStringEnumMemberName("server.versionCheck")]
    ServerDotversionCheck,
    [JsonStringEnumMemberName("serverLicense.read")]
    ServerLicenseDotread,
    [JsonStringEnumMemberName("serverLicense.update")]
    ServerLicenseDotupdate,
    [JsonStringEnumMemberName("serverLicense.delete")]
    ServerLicenseDotdelete,
    [JsonStringEnumMemberName("session.create")]
    SessionDotcreate,
    [JsonStringEnumMemberName("session.read")]
    SessionDotread,
    [JsonStringEnumMemberName("session.update")]
    SessionDotupdate,
    [JsonStringEnumMemberName("session.delete")]
    SessionDotdelete,
    [JsonStringEnumMemberName("session.lock")]
    SessionDotlock,
    [JsonStringEnumMemberName("sharedLink.create")]
    SharedLinkDotcreate,
    [JsonStringEnumMemberName("sharedLink.read")]
    SharedLinkDotread,
    [JsonStringEnumMemberName("sharedLink.update")]
    SharedLinkDotupdate,
    [JsonStringEnumMemberName("sharedLink.delete")]
    SharedLinkDotdelete,
    [JsonStringEnumMemberName("stack.create")]
    StackDotcreate,
    [JsonStringEnumMemberName("stack.read")]
    StackDotread,
    [JsonStringEnumMemberName("stack.update")]
    StackDotupdate,
    [JsonStringEnumMemberName("stack.delete")]
    StackDotdelete,
    [JsonStringEnumMemberName("sync.stream")]
    SyncDotstream,
    [JsonStringEnumMemberName("syncCheckpoint.read")]
    SyncCheckpointDotread,
    [JsonStringEnumMemberName("syncCheckpoint.update")]
    SyncCheckpointDotupdate,
    [JsonStringEnumMemberName("syncCheckpoint.delete")]
    SyncCheckpointDotdelete,
    [JsonStringEnumMemberName("systemConfig.read")]
    SystemConfigDotread,
    [JsonStringEnumMemberName("systemConfig.update")]
    SystemConfigDotupdate,
    [JsonStringEnumMemberName("systemMetadata.read")]
    SystemMetadataDotread,
    [JsonStringEnumMemberName("systemMetadata.update")]
    SystemMetadataDotupdate,
    [JsonStringEnumMemberName("tag.create")]
    TagDotcreate,
    [JsonStringEnumMemberName("tag.read")]
    TagDotread,
    [JsonStringEnumMemberName("tag.update")]
    TagDotupdate,
    [JsonStringEnumMemberName("tag.delete")]
    TagDotdelete,
    [JsonStringEnumMemberName("tag.asset")]
    TagDotasset,
    [JsonStringEnumMemberName("user.read")]
    UserDotread,
    [JsonStringEnumMemberName("user.update")]
    UserDotupdate,
    [JsonStringEnumMemberName("userLicense.create")]
    UserLicenseDotcreate,
    [JsonStringEnumMemberName("userLicense.read")]
    UserLicenseDotread,
    [JsonStringEnumMemberName("userLicense.update")]
    UserLicenseDotupdate,
    [JsonStringEnumMemberName("userLicense.delete")]
    UserLicenseDotdelete,
    [JsonStringEnumMemberName("userOnboarding.read")]
    UserOnboardingDotread,
    [JsonStringEnumMemberName("userOnboarding.update")]
    UserOnboardingDotupdate,
    [JsonStringEnumMemberName("userOnboarding.delete")]
    UserOnboardingDotdelete,
    [JsonStringEnumMemberName("userPreference.read")]
    UserPreferenceDotread,
    [JsonStringEnumMemberName("userPreference.update")]
    UserPreferenceDotupdate,
    [JsonStringEnumMemberName("userProfileImage.create")]
    UserProfileImageDotcreate,
    [JsonStringEnumMemberName("userProfileImage.read")]
    UserProfileImageDotread,
    [JsonStringEnumMemberName("userProfileImage.update")]
    UserProfileImageDotupdate,
    [JsonStringEnumMemberName("userProfileImage.delete")]
    UserProfileImageDotdelete,
    [JsonStringEnumMemberName("queue.read")]
    QueueDotread,
    [JsonStringEnumMemberName("queue.update")]
    QueueDotupdate,
    [JsonStringEnumMemberName("queueJob.create")]
    QueueJobDotcreate,
    [JsonStringEnumMemberName("queueJob.read")]
    QueueJobDotread,
    [JsonStringEnumMemberName("queueJob.update")]
    QueueJobDotupdate,
    [JsonStringEnumMemberName("queueJob.delete")]
    QueueJobDotdelete,
    [JsonStringEnumMemberName("workflow.create")]
    WorkflowDotcreate,
    [JsonStringEnumMemberName("workflow.read")]
    WorkflowDotread,
    [JsonStringEnumMemberName("workflow.update")]
    WorkflowDotupdate,
    [JsonStringEnumMemberName("workflow.delete")]
    WorkflowDotdelete,
    [JsonStringEnumMemberName("adminUser.create")]
    AdminUserDotcreate,
    [JsonStringEnumMemberName("adminUser.read")]
    AdminUserDotread,
    [JsonStringEnumMemberName("adminUser.update")]
    AdminUserDotupdate,
    [JsonStringEnumMemberName("adminUser.delete")]
    AdminUserDotdelete,
    [JsonStringEnumMemberName("adminSession.read")]
    AdminSessionDotread,
    [JsonStringEnumMemberName("adminAuth.unlinkAll")]
    AdminAuthDotunlinkAll,
}
