//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// PersonWithFacesResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/PersonWithFacesResponseDto
/// </summary>
public class PersonWithFacesResponseDto
{
  /// <summary>
  /// Person date of birth
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("birthDate")]
  public DateOnly? BirthDate { get; set; }

  /// <summary>
  /// Person color (hex)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("color")]
  public string? Color { get; set; }

  /// <summary>
  /// Face detections
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("faces")]
  public List<AssetFaceWithoutPersonResponseDto>? Faces { get; set; }

  /// <summary>
  /// Person ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Is favorite
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isFavorite")]
  public bool? IsFavorite { get; set; }

  /// <summary>
  /// Is hidden
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isHidden")]
  public bool IsHidden { get; set; }

  /// <summary>
  /// Person name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// Thumbnail path
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("thumbnailPath")]
  public string? ThumbnailPath { get; set; }

  /// <summary>
  /// Last update date
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
  public DateTime? UpdatedAt { get; set; }
}
