//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// PlacesResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/PlacesResponseDto
/// </summary>
public class PlacesResponseDto
{
  /// <summary>
  /// Administrative level 1 name (state/province)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("admin1name")]
  public string? Admin1name { get; set; }

  /// <summary>
  /// Administrative level 2 name (county/district)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("admin2name")]
  public string? Admin2name { get; set; }

  /// <summary>
  /// Latitude coordinate
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("latitude")]
  public decimal Latitude { get; set; }

  /// <summary>
  /// Longitude coordinate
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("longitude")]
  public decimal Longitude { get; set; }

  /// <summary>
  /// Place name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }
}
