//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// PluginTriggerResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/PluginTriggerResponseDto
/// </summary>
public class PluginTriggerResponseDto
{
  /// <summary>
  /// Context type
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("contextType")]
  public PluginContextType ContextType { get; set; }

  /// <summary>
  /// Trigger type
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public PluginTriggerType Type { get; set; }
}
