//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// PluginResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/PluginResponseDto
/// </summary>
public class PluginResponseDto
{
  /// <summary>
  /// Plugin actions
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("actions")]
  public List<PluginActionResponseDto>? Actions { get; set; }

  /// <summary>
  /// Plugin author
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("author")]
  public string? Author { get; set; }

  /// <summary>
  /// Creation date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public string? CreatedAt { get; set; }

  /// <summary>
  /// Plugin description
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Plugin filters
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("filters")]
  public List<PluginFilterResponseDto>? Filters { get; set; }

  /// <summary>
  /// Plugin ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Plugin name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// Plugin title
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }

  /// <summary>
  /// Last update date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
  public string? UpdatedAt { get; set; }

  /// <summary>
  /// Plugin version
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("version")]
  public string? Version { get; set; }
}
