//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// PluginFilterResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/PluginFilterResponseDto
/// </summary>
public class PluginFilterResponseDto
{
  /// <summary>
  /// Filter description
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Filter ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Method name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("methodName")]
  public string? MethodName { get; set; }

  /// <summary>
  /// Plugin ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("pluginId")]
  public string? PluginId { get; set; }

  /// <summary>
  /// Filter schema
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("schema")]
  public object? Schema { get; set; }

  /// <summary>
  /// Supported contexts
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("supportedContexts")]
  public List<PluginContextType>? SupportedContexts { get; set; }

  /// <summary>
  /// Filter title
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }
}
