//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// PurchaseResponse from OpenAPI schema.
/// Schema path: #/components/schemas/PurchaseResponse
/// </summary>
public class PurchaseResponse
{
  /// <summary>
  /// Date until which to hide buy button
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("hideBuyButtonUntil")]
  public string? HideBuyButtonUntil { get; set; }

  /// <summary>
  /// Whether to show support badge
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("showSupportBadge")]
  public bool ShowSupportBadge { get; set; }
}
