//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// QueueJobResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/QueueJobResponseDto
/// </summary>
public class QueueJobResponseDto
{
  /// <summary>
  /// Job data payload
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("data")]
  public object? Data { get; set; }

  /// <summary>
  /// Job ID
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Job name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public JobName Name { get; set; }

  /// <summary>
  /// Job creation timestamp
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("timestamp")]
  public int Timestamp { get; set; }
}
