//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// QueueStatisticsDto from OpenAPI schema.
/// Schema path: #/components/schemas/QueueStatisticsDto
/// </summary>
public class QueueStatisticsDto
{
  /// <summary>
  /// Number of active jobs
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("active")]
  public int Active { get; set; }

  /// <summary>
  /// Number of completed jobs
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("completed")]
  public int Completed { get; set; }

  /// <summary>
  /// Number of delayed jobs
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("delayed")]
  public int Delayed { get; set; }

  /// <summary>
  /// Number of failed jobs
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("failed")]
  public int Failed { get; set; }

  /// <summary>
  /// Number of paused jobs
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("paused")]
  public int Paused { get; set; }

  /// <summary>
  /// Number of waiting jobs
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("waiting")]
  public int Waiting { get; set; }
}
