//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// QueueCommandDto from OpenAPI schema.
/// Schema path: #/components/schemas/QueueCommandDto
/// </summary>
public class QueueCommandDto
{
  /// <summary>
  /// Queue command to execute
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("command")]
  public QueueCommand Command { get; set; }

  /// <summary>
  /// Force the command execution (if applicable)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("force")]
  public bool? Force { get; set; }
}
