//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// QueueResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/QueueResponseDto
/// </summary>
public class QueueResponseDto
{
  /// <summary>
  /// Whether the queue is paused
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isPaused")]
  public bool IsPaused { get; set; }

  /// <summary>
  /// Queue name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public QueueName Name { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("statistics")]
  public QueueStatisticsDto Statistics { get; set; } = null!;
}
