//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// QueuesResponseLegacyDto from OpenAPI schema.
/// Schema path: #/components/schemas/QueuesResponseLegacyDto
/// </summary>
public class QueuesResponseLegacyDto
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("backgroundTask")]
  public QueueResponseLegacyDto BackgroundTask { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("backupDatabase")]
  public QueueResponseLegacyDto BackupDatabase { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("duplicateDetection")]
  public QueueResponseLegacyDto DuplicateDetection { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("editor")]
  public QueueResponseLegacyDto Editor { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("faceDetection")]
  public QueueResponseLegacyDto FaceDetection { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("facialRecognition")]
  public QueueResponseLegacyDto FacialRecognition { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("library")]
  public QueueResponseLegacyDto Library { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("metadataExtraction")]
  public QueueResponseLegacyDto MetadataExtraction { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("migration")]
  public QueueResponseLegacyDto Migration { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("notifications")]
  public QueueResponseLegacyDto Notifications { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ocr")]
  public QueueResponseLegacyDto Ocr { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("search")]
  public QueueResponseLegacyDto Search { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("sidecar")]
  public QueueResponseLegacyDto Sidecar { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("smartSearch")]
  public QueueResponseLegacyDto SmartSearch { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("storageTemplateMigration")]
  public QueueResponseLegacyDto StorageTemplateMigration { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("thumbnailGeneration")]
  public QueueResponseLegacyDto ThumbnailGeneration { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("videoConversion")]
  public QueueResponseLegacyDto VideoConversion { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("workflow")]
  public QueueResponseLegacyDto Workflow { get; set; } = null!;
}
