//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// ReverseGeocodingStateResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/ReverseGeocodingStateResponseDto
/// </summary>
public class ReverseGeocodingStateResponseDto
{
  /// <summary>
  /// Last import file name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("lastImportFileName")]
  public string? LastImportFileName { get; set; }

  /// <summary>
  /// Last update timestamp
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("lastUpdate")]
  public string? LastUpdate { get; set; }
}
