//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SearchResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/SearchResponseDto
/// </summary>
public class SearchResponseDto
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("albums")]
  public SearchAlbumResponseDto Albums { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assets")]
  public SearchAssetResponseDto Assets { get; set; } = null!;
}
