//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SearchExploreItem from OpenAPI schema.
/// Schema path: #/components/schemas/SearchExploreItem
/// </summary>
public class SearchExploreItem
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("data")]
  public AssetResponseDto Data { get; set; } = null!;

  /// <summary>
  /// Explore value
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("value")]
  public string? Value { get; set; }
}
