//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SearchAssetStatisticsRequest from OpenAPI schema.
/// Schema path: #/components/schemas/SearchAssetStatisticsRequest
/// </summary>
public class SearchAssetStatisticsRequest
{
  /// <summary>
  /// Filter by album IDs
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("albumIds")]
  public List<Guid>? AlbumIds { get; set; }

  /// <summary>
  /// Filter by city name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("city")]
  public string? City { get; set; }

  /// <summary>
  /// Filter by country name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("country")]
  public string? Country { get; set; }

  /// <summary>
  /// Filter by creation date (after)
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("createdAfter")]
  public DateTime? CreatedAfter { get; set; }

  /// <summary>
  /// Filter by creation date (before)
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("createdBefore")]
  public DateTime? CreatedBefore { get; set; }

  /// <summary>
  /// Filter by description text
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Device ID to filter by
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("deviceId")]
  public string? DeviceId { get; set; }

  /// <summary>
  /// Filter by encoded status
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("isEncoded")]
  public bool? IsEncoded { get; set; }

  /// <summary>
  /// Filter by favorite status
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("isFavorite")]
  public bool? IsFavorite { get; set; }

  /// <summary>
  /// Filter by motion photo status
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("isMotion")]
  public bool? IsMotion { get; set; }

  /// <summary>
  /// Filter assets not in any album
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("isNotInAlbum")]
  public bool? IsNotInAlbum { get; set; }

  /// <summary>
  /// Filter by offline status
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("isOffline")]
  public bool? IsOffline { get; set; }

  /// <summary>
  /// Filter by lens model
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("lensModel")]
  public string? LensModel { get; set; }

  /// <summary>
  /// Library ID to filter by
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("libraryId")]
  public Guid? LibraryId { get; set; }

  /// <summary>
  /// Filter by camera make
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("make")]
  public string? Make { get; set; }

  /// <summary>
  /// Filter by camera model
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("model")]
  public string? Model { get; set; }

  /// <summary>
  /// Filter by OCR text content
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("ocr")]
  public string? Ocr { get; set; }

  /// <summary>
  /// Filter by person IDs
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("personIds")]
  public List<Guid>? PersonIds { get; set; }

  /// <summary>
  /// Filter by rating [1-5], or null for unrated
  /// </summary>
  [Range(-1, 5)]
  [System.Text.Json.Serialization.JsonPropertyName("rating")]
  public decimal? Rating { get; set; }

  /// <summary>
  /// Filter by state/province name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("state")]
  public string? State { get; set; }

  /// <summary>
  /// Filter by tag IDs
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tagIds")]
  public List<Guid>? TagIds { get; set; }

  /// <summary>
  /// Filter by taken date (after)
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("takenAfter")]
  public DateTime? TakenAfter { get; set; }

  /// <summary>
  /// Filter by taken date (before)
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("takenBefore")]
  public DateTime? TakenBefore { get; set; }

  /// <summary>
  /// Filter by trash date (after)
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("trashedAfter")]
  public DateTime? TrashedAfter { get; set; }

  /// <summary>
  /// Filter by trash date (before)
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("trashedBefore")]
  public DateTime? TrashedBefore { get; set; }

  /// <summary>
  /// Asset type filter
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public AssetTypeEnum? Type { get; set; }

  /// <summary>
  /// Filter by update date (after)
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("updatedAfter")]
  public DateTime? UpdatedAfter { get; set; }

  /// <summary>
  /// Filter by update date (before)
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("updatedBefore")]
  public DateTime? UpdatedBefore { get; set; }

  /// <summary>
  /// Filter by visibility
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("visibility")]
  public AssetVisibility? Visibility { get; set; }
}
