//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SearchAssetResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/SearchAssetResponseDto
/// </summary>
public class SearchAssetResponseDto
{
  /// <summary>
  /// Number of assets in this page
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("count")]
  public int Count { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("facets")]
  public List<SearchFacetResponseDto>? Facets { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("items")]
  public List<AssetResponseDto>? Items { get; set; }

  /// <summary>
  /// Next page token
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("nextPage")]
  public string? NextPage { get; set; }

  /// <summary>
  /// Total number of matching assets
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("total")]
  public int Total { get; set; }
}
