//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SendTestEmailAdminRequest from OpenAPI schema.
/// Schema path: #/components/schemas/SendTestEmailAdminRequest
/// </summary>
public class SendTestEmailAdminRequest
{
  /// <summary>
  /// Whether SMTP email notifications are enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool Enabled { get; set; }

  /// <summary>
  /// Email address to send from
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("from")]
  public string? From { get; set; }

  /// <summary>
  /// Email address for replies
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("replyTo")]
  public string? ReplyTo { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("transport")]
  public required SystemConfigSmtpTransportDto Transport { get; set; }
}
