//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// ServerMediaTypesResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/ServerMediaTypesResponseDto
/// </summary>
public class ServerMediaTypesResponseDto
{
  /// <summary>
  /// Supported image MIME types
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("image")]
  public List<string?>? Image { get; set; }

  /// <summary>
  /// Supported sidecar MIME types
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("sidecar")]
  public List<string?>? Sidecar { get; set; }

  /// <summary>
  /// Supported video MIME types
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("video")]
  public List<string?>? Video { get; set; }
}
