//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// ServerConfigDto from OpenAPI schema.
/// Schema path: #/components/schemas/ServerConfigDto
/// </summary>
public class ServerConfigDto
{
  /// <summary>
  /// External domain URL
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("externalDomain")]
  public string? ExternalDomain { get; set; }

  /// <summary>
  /// Whether the server has been initialized
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isInitialized")]
  public bool IsInitialized { get; set; }

  /// <summary>
  /// Whether the admin has completed onboarding
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isOnboarded")]
  public bool IsOnboarded { get; set; }

  /// <summary>
  /// Login page message
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("loginPageMessage")]
  public string? LoginPageMessage { get; set; }

  /// <summary>
  /// Whether maintenance mode is active
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("maintenanceMode")]
  public bool MaintenanceMode { get; set; }

  /// <summary>
  /// Map dark style URL
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("mapDarkStyleUrl")]
  public string? MapDarkStyleUrl { get; set; }

  /// <summary>
  /// Map light style URL
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("mapLightStyleUrl")]
  public string? MapLightStyleUrl { get; set; }

  /// <summary>
  /// OAuth button text
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("oauthButtonText")]
  public string? OauthButtonText { get; set; }

  /// <summary>
  /// Whether public user registration is enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("publicUsers")]
  public bool PublicUsers { get; set; }

  /// <summary>
  /// Number of days before trashed assets are permanently deleted
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("trashDays")]
  public int TrashDays { get; set; }

  /// <summary>
  /// Delay in days before deleted users are permanently removed
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("userDeleteDelay")]
  public int UserDeleteDelay { get; set; }
}
