//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// ServerAboutResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/ServerAboutResponseDto
/// </summary>
public class ServerAboutResponseDto
{
  /// <summary>
  /// Build identifier
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("build")]
  public string? Build { get; set; }

  /// <summary>
  /// Build image name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("buildImage")]
  public string? BuildImage { get; set; }

  /// <summary>
  /// Build image URL
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("buildImageUrl")]
  public string? BuildImageUrl { get; set; }

  /// <summary>
  /// Build URL
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("buildUrl")]
  public string? BuildUrl { get; set; }

  /// <summary>
  /// ExifTool version
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("exiftool")]
  public string? Exiftool { get; set; }

  /// <summary>
  /// FFmpeg version
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("ffmpeg")]
  public string? Ffmpeg { get; set; }

  /// <summary>
  /// ImageMagick version
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("imagemagick")]
  public string? Imagemagick { get; set; }

  /// <summary>
  /// libvips version
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("libvips")]
  public string? Libvips { get; set; }

  /// <summary>
  /// Whether the server is licensed
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("licensed")]
  public bool Licensed { get; set; }

  /// <summary>
  /// Node.js version
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("nodejs")]
  public string? Nodejs { get; set; }

  /// <summary>
  /// Repository name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("repository")]
  public string? Repository { get; set; }

  /// <summary>
  /// Repository URL
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("repositoryUrl")]
  public string? RepositoryUrl { get; set; }

  /// <summary>
  /// Source commit hash
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("sourceCommit")]
  public string? SourceCommit { get; set; }

  /// <summary>
  /// Source reference (branch/tag)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("sourceRef")]
  public string? SourceRef { get; set; }

  /// <summary>
  /// Source URL
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("sourceUrl")]
  public string? SourceUrl { get; set; }

  /// <summary>
  /// Third-party bug/feature URL
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("thirdPartyBugFeatureUrl")]
  public string? ThirdPartyBugFeatureUrl { get; set; }

  /// <summary>
  /// Third-party documentation URL
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("thirdPartyDocumentationUrl")]
  public string? ThirdPartyDocumentationUrl { get; set; }

  /// <summary>
  /// Third-party source URL
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("thirdPartySourceUrl")]
  public string? ThirdPartySourceUrl { get; set; }

  /// <summary>
  /// Third-party support URL
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("thirdPartySupportUrl")]
  public string? ThirdPartySupportUrl { get; set; }

  /// <summary>
  /// Server version
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("version")]
  public string? Version { get; set; }

  /// <summary>
  /// URL to version information
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("versionUrl")]
  public string? VersionUrl { get; set; }
}
