//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// ServerApkLinksDto from OpenAPI schema.
/// Schema path: #/components/schemas/ServerApkLinksDto
/// </summary>
public class ServerApkLinksDto
{
  /// <summary>
  /// APK download link for ARM64 v8a architecture
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("arm64v8a")]
  public string? Arm64v8a { get; set; }

  /// <summary>
  /// APK download link for ARM EABI v7a architecture
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("armeabiv7a")]
  public string? Armeabiv7a { get; set; }

  /// <summary>
  /// APK download link for universal architecture
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("universal")]
  public string? Universal { get; set; }

  /// <summary>
  /// APK download link for x86_64 architecture
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("x86_64")]
  public string? X86_64 { get; set; }
}
