//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// ServerStorageResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/ServerStorageResponseDto
/// </summary>
public class ServerStorageResponseDto
{
  /// <summary>
  /// Available disk space (human-readable format)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("diskAvailable")]
  public string? DiskAvailable { get; set; }

  /// <summary>
  /// Available disk space in bytes
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("diskAvailableRaw")]
  public long DiskAvailableRaw { get; set; }

  /// <summary>
  /// Total disk size (human-readable format)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("diskSize")]
  public string? DiskSize { get; set; }

  /// <summary>
  /// Total disk size in bytes
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("diskSizeRaw")]
  public long DiskSizeRaw { get; set; }

  /// <summary>
  /// Disk usage percentage (0-100)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("diskUsagePercentage")]
  public double DiskUsagePercentage { get; set; }

  /// <summary>
  /// Used disk space (human-readable format)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("diskUse")]
  public string? DiskUse { get; set; }

  /// <summary>
  /// Used disk space in bytes
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("diskUseRaw")]
  public long DiskUseRaw { get; set; }
}
