//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// ServerVersionHistoryResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/ServerVersionHistoryResponseDto
/// </summary>
public class ServerVersionHistoryResponseDto
{
  /// <summary>
  /// When this version was first seen
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public DateTime CreatedAt { get; set; }

  /// <summary>
  /// Version history entry ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Version string
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("version")]
  public string? Version { get; set; }
}
