//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// ServerStatsResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/ServerStatsResponseDto
/// </summary>
public class ServerStatsResponseDto
{
  /// <summary>
  /// Total number of photos
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("photos")]
  public int Photos { get; set; }

  /// <summary>
  /// Total storage usage in bytes
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("usage")]
  public long Usage { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("usageByUser")]
  public List<UsageByUserDto>? UsageByUser { get; set; }

  /// <summary>
  /// Storage usage for photos in bytes
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("usagePhotos")]
  public long UsagePhotos { get; set; }

  /// <summary>
  /// Storage usage for videos in bytes
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("usageVideos")]
  public long UsageVideos { get; set; }

  /// <summary>
  /// Total number of videos
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("videos")]
  public int Videos { get; set; }
}
