//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// ServerFeaturesDto from OpenAPI schema.
/// Schema path: #/components/schemas/ServerFeaturesDto
/// </summary>
public class ServerFeaturesDto
{
  /// <summary>
  /// Whether config file is available
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("configFile")]
  public bool ConfigFile { get; set; }

  /// <summary>
  /// Whether duplicate detection is enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("duplicateDetection")]
  public bool DuplicateDetection { get; set; }

  /// <summary>
  /// Whether email notifications are enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public bool Email { get; set; }

  /// <summary>
  /// Whether facial recognition is enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("facialRecognition")]
  public bool FacialRecognition { get; set; }

  /// <summary>
  /// Whether face import is enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("importFaces")]
  public bool ImportFaces { get; set; }

  /// <summary>
  /// Whether map feature is enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("map")]
  public bool Map { get; set; }

  /// <summary>
  /// Whether OAuth is enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("oauth")]
  public bool Oauth { get; set; }

  /// <summary>
  /// Whether OAuth auto-launch is enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("oauthAutoLaunch")]
  public bool OauthAutoLaunch { get; set; }

  /// <summary>
  /// Whether OCR is enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ocr")]
  public bool Ocr { get; set; }

  /// <summary>
  /// Whether password login is enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("passwordLogin")]
  public bool PasswordLogin { get; set; }

  /// <summary>
  /// Whether reverse geocoding is enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("reverseGeocoding")]
  public bool ReverseGeocoding { get; set; }

  /// <summary>
  /// Whether search is enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("search")]
  public bool Search { get; set; }

  /// <summary>
  /// Whether sidecar files are supported
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("sidecar")]
  public bool Sidecar { get; set; }

  /// <summary>
  /// Whether smart search is enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("smartSearch")]
  public bool SmartSearch { get; set; }

  /// <summary>
  /// Whether trash feature is enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("trash")]
  public bool Trash { get; set; }
}
