//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SessionUnlockDto from OpenAPI schema.
/// Schema path: #/components/schemas/SessionUnlockDto
/// </summary>
public class SessionUnlockDto
{
  /// <summary>
  /// User password (required if PIN code is not provided)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  /// <summary>
  /// New PIN code (4-6 digits)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("pinCode")]
  public string? PinCode { get; set; }
}
