//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SessionResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/SessionResponseDto
/// </summary>
public class SessionResponseDto
{
  /// <summary>
  /// App version
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("appVersion")]
  public string? AppVersion { get; set; }

  /// <summary>
  /// Creation date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public string? CreatedAt { get; set; }

  /// <summary>
  /// Is current session
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("current")]
  public bool Current { get; set; }

  /// <summary>
  /// Device OS
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("deviceOS")]
  public string? DeviceOS { get; set; }

  /// <summary>
  /// Device type
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("deviceType")]
  public string? DeviceType { get; set; }

  /// <summary>
  /// Expiration date
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("expiresAt")]
  public string? ExpiresAt { get; set; }

  /// <summary>
  /// Session ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Is pending sync reset
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isPendingSyncReset")]
  public bool IsPendingSyncReset { get; set; }

  /// <summary>
  /// Last update date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
  public string? UpdatedAt { get; set; }
}
