//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SetMaintenanceModeRequest from OpenAPI schema.
/// Schema path: #/components/schemas/SetMaintenanceModeRequest
/// </summary>
public class SetMaintenanceModeRequest
{
  /// <summary>
  /// Maintenance action
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("action")]
  public MaintenanceAction Action { get; set; }

  /// <summary>
  /// Restore backup filename
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("restoreBackupFilename")]
  public string? RestoreBackupFilename { get; set; }
}
