//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SharedLinkResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/SharedLinkResponseDto
/// </summary>
public class SharedLinkResponseDto
{
  [System.Text.Json.Serialization.JsonPropertyName("album")]
  public AlbumResponseDto? Album { get; set; }

  /// <summary>
  /// Allow downloads
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("allowDownload")]
  public bool AllowDownload { get; set; }

  /// <summary>
  /// Allow uploads
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("allowUpload")]
  public bool AllowUpload { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assets")]
  public List<AssetResponseDto>? Assets { get; set; }

  /// <summary>
  /// Creation date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public DateTime CreatedAt { get; set; }

  /// <summary>
  /// Link description
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Expiration date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("expiresAt")]
  public DateTime? ExpiresAt { get; set; }

  /// <summary>
  /// Shared link ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Encryption key (base64url)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }

  /// <summary>
  /// Has password
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  /// <summary>
  /// Show metadata
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("showMetadata")]
  public bool ShowMetadata { get; set; }

  /// <summary>
  /// Custom URL slug
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("slug")]
  public string? Slug { get; set; }

  /// <summary>
  /// Access token
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("token")]
  public string? Token { get; set; }

  /// <summary>
  /// Shared link type
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public SharedLinkType Type { get; set; }

  /// <summary>
  /// Owner user ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("userId")]
  public string? UserId { get; set; }
}
