//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SharedLinkEditDto from OpenAPI schema.
/// Schema path: #/components/schemas/SharedLinkEditDto
/// </summary>
public class SharedLinkEditDto
{
  /// <summary>
  /// Allow downloads
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("allowDownload")]
  public bool? AllowDownload { get; set; }

  /// <summary>
  /// Allow uploads
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("allowUpload")]
  public bool? AllowUpload { get; set; }

  /// <summary>
  /// Whether to change the expiry time. Few clients cannot send null to set the expiryTime to never. Setting this flag and not sending expiryAt is considered as null instead. Clients that can send null values can ignore this.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("changeExpiryTime")]
  public bool? ChangeExpiryTime { get; set; }

  /// <summary>
  /// Link description
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Expiration date
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("expiresAt")]
  public DateTime? ExpiresAt { get; set; }

  /// <summary>
  /// Link password
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  /// <summary>
  /// Show metadata
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("showMetadata")]
  public bool? ShowMetadata { get; set; }

  /// <summary>
  /// Custom URL slug
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("slug")]
  public string? Slug { get; set; }
}
