//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SyncUserV1 from OpenAPI schema.
/// Schema path: #/components/schemas/SyncUserV1
/// </summary>
public class SyncUserV1
{
  /// <summary>
  /// User avatar color
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("avatarColor")]
  public UserAvatarColor AvatarColor { get; set; }

  /// <summary>
  /// User deleted at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("deletedAt")]
  public DateTime? DeletedAt { get; set; }

  /// <summary>
  /// User email
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  /// <summary>
  /// User has profile image
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("hasProfileImage")]
  public bool HasProfileImage { get; set; }

  /// <summary>
  /// User ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// User name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// User profile changed at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("profileChangedAt")]
  public DateTime ProfileChangedAt { get; set; }
}
