//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SyncStackV1 from OpenAPI schema.
/// Schema path: #/components/schemas/SyncStackV1
/// </summary>
public class SyncStackV1
{
  /// <summary>
  /// Created at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public DateTime CreatedAt { get; set; }

  /// <summary>
  /// Stack ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Owner ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ownerId")]
  public string? OwnerId { get; set; }

  /// <summary>
  /// Primary asset ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("primaryAssetId")]
  public string? PrimaryAssetId { get; set; }

  /// <summary>
  /// Updated at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
  public DateTime UpdatedAt { get; set; }
}
