//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SyncAssetEditV1 from OpenAPI schema.
/// Schema path: #/components/schemas/SyncAssetEditV1
/// </summary>
public class SyncAssetEditV1
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("action")]
  public AssetEditAction Action { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assetId")]
  public string? AssetId { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("parameters")]
  public object? Parameters { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("sequence")]
  public int Sequence { get; set; }
}
