//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SyncPersonV1 from OpenAPI schema.
/// Schema path: #/components/schemas/SyncPersonV1
/// </summary>
public class SyncPersonV1
{
  /// <summary>
  /// Birth date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("birthDate")]
  public DateTime? BirthDate { get; set; }

  /// <summary>
  /// Color
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("color")]
  public string? Color { get; set; }

  /// <summary>
  /// Created at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public DateTime CreatedAt { get; set; }

  /// <summary>
  /// Face asset ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("faceAssetId")]
  public string? FaceAssetId { get; set; }

  /// <summary>
  /// Person ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Is favorite
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isFavorite")]
  public bool IsFavorite { get; set; }

  /// <summary>
  /// Is hidden
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isHidden")]
  public bool IsHidden { get; set; }

  /// <summary>
  /// Person name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// Owner ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ownerId")]
  public string? OwnerId { get; set; }

  /// <summary>
  /// Updated at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
  public DateTime UpdatedAt { get; set; }
}
