//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SyncUserMetadataDeleteV1 from OpenAPI schema.
/// Schema path: #/components/schemas/SyncUserMetadataDeleteV1
/// </summary>
public class SyncUserMetadataDeleteV1
{
  /// <summary>
  /// User metadata key
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public UserMetadataKey Key { get; set; }

  /// <summary>
  /// User ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("userId")]
  public string? UserId { get; set; }
}
