//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SyncAssetExifV1 from OpenAPI schema.
/// Schema path: #/components/schemas/SyncAssetExifV1
/// </summary>
public class SyncAssetExifV1
{
  /// <summary>
  /// Asset ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assetId")]
  public string? AssetId { get; set; }

  /// <summary>
  /// City
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("city")]
  public string? City { get; set; }

  /// <summary>
  /// Country
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("country")]
  public string? Country { get; set; }

  /// <summary>
  /// Date time original
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("dateTimeOriginal")]
  public DateTime? DateTimeOriginal { get; set; }

  /// <summary>
  /// Description
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Exif image height
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("exifImageHeight")]
  public int? ExifImageHeight { get; set; }

  /// <summary>
  /// Exif image width
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("exifImageWidth")]
  public int? ExifImageWidth { get; set; }

  /// <summary>
  /// Exposure time
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("exposureTime")]
  public string? ExposureTime { get; set; }

  /// <summary>
  /// F number
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("fNumber")]
  public double? FNumber { get; set; }

  /// <summary>
  /// File size in byte
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("fileSizeInByte")]
  public int? FileSizeInByte { get; set; }

  /// <summary>
  /// Focal length
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("focalLength")]
  public double? FocalLength { get; set; }

  /// <summary>
  /// FPS
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("fps")]
  public double? Fps { get; set; }

  /// <summary>
  /// ISO
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("iso")]
  public int? Iso { get; set; }

  /// <summary>
  /// Latitude
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("latitude")]
  public double? Latitude { get; set; }

  /// <summary>
  /// Lens model
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("lensModel")]
  public string? LensModel { get; set; }

  /// <summary>
  /// Longitude
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("longitude")]
  public double? Longitude { get; set; }

  /// <summary>
  /// Make
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("make")]
  public string? Make { get; set; }

  /// <summary>
  /// Model
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("model")]
  public string? Model { get; set; }

  /// <summary>
  /// Modify date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("modifyDate")]
  public DateTime? ModifyDate { get; set; }

  /// <summary>
  /// Orientation
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("orientation")]
  public string? Orientation { get; set; }

  /// <summary>
  /// Profile description
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("profileDescription")]
  public string? ProfileDescription { get; set; }

  /// <summary>
  /// Projection type
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("projectionType")]
  public string? ProjectionType { get; set; }

  /// <summary>
  /// Rating
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("rating")]
  public int? Rating { get; set; }

  /// <summary>
  /// State
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("state")]
  public string? State { get; set; }

  /// <summary>
  /// Time zone
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("timeZone")]
  public string? TimeZone { get; set; }
}
