using System;
using System.Text.Json.Serialization;

namespace Apigen.Immich.Models;

/// <summary>
/// Sync entity type
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum SyncEntityType
{
    [JsonStringEnumMemberName("AuthUserV1")]
    AuthUserV1,
    [JsonStringEnumMemberName("UserV1")]
    UserV1,
    [JsonStringEnumMemberName("UserDeleteV1")]
    UserDeleteV1,
    [JsonStringEnumMemberName("AssetV1")]
    AssetV1,
    [JsonStringEnumMemberName("AssetDeleteV1")]
    AssetDeleteV1,
    [JsonStringEnumMemberName("AssetExifV1")]
    AssetExifV1,
    [JsonStringEnumMemberName("AssetEditV1")]
    AssetEditV1,
    [JsonStringEnumMemberName("AssetEditDeleteV1")]
    AssetEditDeleteV1,
    [JsonStringEnumMemberName("AssetMetadataV1")]
    AssetMetadataV1,
    [JsonStringEnumMemberName("AssetMetadataDeleteV1")]
    AssetMetadataDeleteV1,
    [JsonStringEnumMemberName("PartnerV1")]
    PartnerV1,
    [JsonStringEnumMemberName("PartnerDeleteV1")]
    PartnerDeleteV1,
    [JsonStringEnumMemberName("PartnerAssetV1")]
    PartnerAssetV1,
    [JsonStringEnumMemberName("PartnerAssetBackfillV1")]
    PartnerAssetBackfillV1,
    [JsonStringEnumMemberName("PartnerAssetDeleteV1")]
    PartnerAssetDeleteV1,
    [JsonStringEnumMemberName("PartnerAssetExifV1")]
    PartnerAssetExifV1,
    [JsonStringEnumMemberName("PartnerAssetExifBackfillV1")]
    PartnerAssetExifBackfillV1,
    [JsonStringEnumMemberName("PartnerStackBackfillV1")]
    PartnerStackBackfillV1,
    [JsonStringEnumMemberName("PartnerStackDeleteV1")]
    PartnerStackDeleteV1,
    [JsonStringEnumMemberName("PartnerStackV1")]
    PartnerStackV1,
    [JsonStringEnumMemberName("AlbumV1")]
    AlbumV1,
    [JsonStringEnumMemberName("AlbumDeleteV1")]
    AlbumDeleteV1,
    [JsonStringEnumMemberName("AlbumUserV1")]
    AlbumUserV1,
    [JsonStringEnumMemberName("AlbumUserBackfillV1")]
    AlbumUserBackfillV1,
    [JsonStringEnumMemberName("AlbumUserDeleteV1")]
    AlbumUserDeleteV1,
    [JsonStringEnumMemberName("AlbumAssetCreateV1")]
    AlbumAssetCreateV1,
    [JsonStringEnumMemberName("AlbumAssetUpdateV1")]
    AlbumAssetUpdateV1,
    [JsonStringEnumMemberName("AlbumAssetBackfillV1")]
    AlbumAssetBackfillV1,
    [JsonStringEnumMemberName("AlbumAssetExifCreateV1")]
    AlbumAssetExifCreateV1,
    [JsonStringEnumMemberName("AlbumAssetExifUpdateV1")]
    AlbumAssetExifUpdateV1,
    [JsonStringEnumMemberName("AlbumAssetExifBackfillV1")]
    AlbumAssetExifBackfillV1,
    [JsonStringEnumMemberName("AlbumToAssetV1")]
    AlbumToAssetV1,
    [JsonStringEnumMemberName("AlbumToAssetDeleteV1")]
    AlbumToAssetDeleteV1,
    [JsonStringEnumMemberName("AlbumToAssetBackfillV1")]
    AlbumToAssetBackfillV1,
    [JsonStringEnumMemberName("MemoryV1")]
    MemoryV1,
    [JsonStringEnumMemberName("MemoryDeleteV1")]
    MemoryDeleteV1,
    [JsonStringEnumMemberName("MemoryToAssetV1")]
    MemoryToAssetV1,
    [JsonStringEnumMemberName("MemoryToAssetDeleteV1")]
    MemoryToAssetDeleteV1,
    [JsonStringEnumMemberName("StackV1")]
    StackV1,
    [JsonStringEnumMemberName("StackDeleteV1")]
    StackDeleteV1,
    [JsonStringEnumMemberName("PersonV1")]
    PersonV1,
    [JsonStringEnumMemberName("PersonDeleteV1")]
    PersonDeleteV1,
    [JsonStringEnumMemberName("AssetFaceV1")]
    AssetFaceV1,
    [JsonStringEnumMemberName("AssetFaceV2")]
    AssetFaceV2,
    [JsonStringEnumMemberName("AssetFaceDeleteV1")]
    AssetFaceDeleteV1,
    [JsonStringEnumMemberName("UserMetadataV1")]
    UserMetadataV1,
    [JsonStringEnumMemberName("UserMetadataDeleteV1")]
    UserMetadataDeleteV1,
    [JsonStringEnumMemberName("SyncAckV1")]
    SyncAckV1,
    [JsonStringEnumMemberName("SyncResetV1")]
    SyncResetV1,
    [JsonStringEnumMemberName("SyncCompleteV1")]
    SyncCompleteV1,
}
