//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SyncAssetEditDeleteV1 from OpenAPI schema.
/// Schema path: #/components/schemas/SyncAssetEditDeleteV1
/// </summary>
public class SyncAssetEditDeleteV1
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("editId")]
  public string? EditId { get; set; }
}
