//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SyncMemoryV1 from OpenAPI schema.
/// Schema path: #/components/schemas/SyncMemoryV1
/// </summary>
public class SyncMemoryV1
{
  /// <summary>
  /// Created at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public DateTime CreatedAt { get; set; }

  /// <summary>
  /// Data
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("data")]
  public object? Data { get; set; }

  /// <summary>
  /// Deleted at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("deletedAt")]
  public DateTime? DeletedAt { get; set; }

  /// <summary>
  /// Hide at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("hideAt")]
  public DateTime? HideAt { get; set; }

  /// <summary>
  /// Memory ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Is saved
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isSaved")]
  public bool IsSaved { get; set; }

  /// <summary>
  /// Memory at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("memoryAt")]
  public DateTime MemoryAt { get; set; }

  /// <summary>
  /// Owner ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ownerId")]
  public string? OwnerId { get; set; }

  /// <summary>
  /// Seen at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("seenAt")]
  public DateTime? SeenAt { get; set; }

  /// <summary>
  /// Show at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("showAt")]
  public DateTime? ShowAt { get; set; }

  /// <summary>
  /// Memory type
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public MemoryType Type { get; set; }

  /// <summary>
  /// Updated at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
  public DateTime UpdatedAt { get; set; }
}
