//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SyncAssetFaceV1 from OpenAPI schema.
/// Schema path: #/components/schemas/SyncAssetFaceV1
/// </summary>
public class SyncAssetFaceV1
{
  /// <summary>
  /// Asset ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assetId")]
  public string? AssetId { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("boundingBoxX1")]
  public int BoundingBoxX1 { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("boundingBoxX2")]
  public int BoundingBoxX2 { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("boundingBoxY1")]
  public int BoundingBoxY1 { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("boundingBoxY2")]
  public int BoundingBoxY2 { get; set; }

  /// <summary>
  /// Asset face ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("imageHeight")]
  public int ImageHeight { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("imageWidth")]
  public int ImageWidth { get; set; }

  /// <summary>
  /// Person ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("personId")]
  public string? PersonId { get; set; }

  /// <summary>
  /// Source type
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("sourceType")]
  public string? SourceType { get; set; }
}
