//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SyncAuthUserV1 from OpenAPI schema.
/// Schema path: #/components/schemas/SyncAuthUserV1
/// </summary>
public class SyncAuthUserV1
{
  /// <summary>
  /// User avatar color
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("avatarColor")]
  public UserAvatarColor AvatarColor { get; set; }

  /// <summary>
  /// User deleted at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("deletedAt")]
  public DateTime? DeletedAt { get; set; }

  /// <summary>
  /// User email
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  /// <summary>
  /// User has profile image
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("hasProfileImage")]
  public bool HasProfileImage { get; set; }

  /// <summary>
  /// User ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// User is admin
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isAdmin")]
  public bool IsAdmin { get; set; }

  /// <summary>
  /// User name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// User OAuth ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("oauthId")]
  public string? OauthId { get; set; }

  /// <summary>
  /// User pin code
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("pinCode")]
  public string? PinCode { get; set; }

  /// <summary>
  /// User profile changed at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("profileChangedAt")]
  public DateTime ProfileChangedAt { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("quotaSizeInBytes")]
  public int? QuotaSizeInBytes { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("quotaUsageInBytes")]
  public int QuotaUsageInBytes { get; set; }

  /// <summary>
  /// User storage label
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("storageLabel")]
  public string? StorageLabel { get; set; }
}
