//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SyncAlbumV1 from OpenAPI schema.
/// Schema path: #/components/schemas/SyncAlbumV1
/// </summary>
public class SyncAlbumV1
{
  /// <summary>
  /// Created at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public DateTime CreatedAt { get; set; }

  /// <summary>
  /// Album description
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Album ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Is activity enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isActivityEnabled")]
  public bool IsActivityEnabled { get; set; }

  /// <summary>
  /// Album name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("order")]
  public AssetOrder Order { get; set; }

  /// <summary>
  /// Owner ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ownerId")]
  public string? OwnerId { get; set; }

  /// <summary>
  /// Thumbnail asset ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("thumbnailAssetId")]
  public string? ThumbnailAssetId { get; set; }

  /// <summary>
  /// Updated at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
  public DateTime UpdatedAt { get; set; }
}
