//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SyncAssetV1 from OpenAPI schema.
/// Schema path: #/components/schemas/SyncAssetV1
/// </summary>
public class SyncAssetV1
{
  /// <summary>
  /// Checksum
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("checksum")]
  public string? Checksum { get; set; }

  /// <summary>
  /// Deleted at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("deletedAt")]
  public DateTime? DeletedAt { get; set; }

  /// <summary>
  /// Duration
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("duration")]
  public string? Duration { get; set; }

  /// <summary>
  /// File created at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("fileCreatedAt")]
  public DateTime? FileCreatedAt { get; set; }

  /// <summary>
  /// File modified at
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("fileModifiedAt")]
  public DateTime? FileModifiedAt { get; set; }

  /// <summary>
  /// Asset height
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("height")]
  public int? Height { get; set; }

  /// <summary>
  /// Asset ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Is edited
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isEdited")]
  public bool IsEdited { get; set; }

  /// <summary>
  /// Is favorite
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isFavorite")]
  public bool IsFavorite { get; set; }

  /// <summary>
  /// Library ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("libraryId")]
  public string? LibraryId { get; set; }

  /// <summary>
  /// Live photo video ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("livePhotoVideoId")]
  public string? LivePhotoVideoId { get; set; }

  /// <summary>
  /// Local date time
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("localDateTime")]
  public DateTime? LocalDateTime { get; set; }

  /// <summary>
  /// Original file name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("originalFileName")]
  public string? OriginalFileName { get; set; }

  /// <summary>
  /// Owner ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ownerId")]
  public string? OwnerId { get; set; }

  /// <summary>
  /// Stack ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("stackId")]
  public string? StackId { get; set; }

  /// <summary>
  /// Thumbhash
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("thumbhash")]
  public string? Thumbhash { get; set; }

  /// <summary>
  /// Asset type
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public AssetTypeEnum Type { get; set; }

  /// <summary>
  /// Asset visibility
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("visibility")]
  public AssetVisibility Visibility { get; set; }

  /// <summary>
  /// Asset width
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("width")]
  public int? Width { get; set; }
}
