//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SyncPartnerV1 from OpenAPI schema.
/// Schema path: #/components/schemas/SyncPartnerV1
/// </summary>
public class SyncPartnerV1
{
  /// <summary>
  /// In timeline
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("inTimeline")]
  public bool InTimeline { get; set; }

  /// <summary>
  /// Shared by ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("sharedById")]
  public string? SharedById { get; set; }

  /// <summary>
  /// Shared with ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("sharedWithId")]
  public string? SharedWithId { get; set; }
}
