//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SyncAssetMetadataV1 from OpenAPI schema.
/// Schema path: #/components/schemas/SyncAssetMetadataV1
/// </summary>
public class SyncAssetMetadataV1
{
  /// <summary>
  /// Asset ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assetId")]
  public string? AssetId { get; set; }

  /// <summary>
  /// Key
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }

  /// <summary>
  /// Value
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("value")]
  public object? Value { get; set; }
}
