//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SystemConfigStorageTemplateDto from OpenAPI schema.
/// Schema path: #/components/schemas/SystemConfigStorageTemplateDto
/// </summary>
public class SystemConfigStorageTemplateDto
{
  /// <summary>
  /// Enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool Enabled { get; set; }

  /// <summary>
  /// Hash verification enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("hashVerificationEnabled")]
  public bool HashVerificationEnabled { get; set; }

  /// <summary>
  /// Template
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("template")]
  public string? Template { get; set; }
}
