//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SystemConfigDto from OpenAPI schema.
/// Schema path: #/components/schemas/SystemConfigDto
/// </summary>
public class SystemConfigDto
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("backup")]
  public SystemConfigBackupsDto Backup { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ffmpeg")]
  public SystemConfigFFmpegDto Ffmpeg { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("image")]
  public SystemConfigImageDto Image { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("job")]
  public SystemConfigJobDto Job { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("library")]
  public SystemConfigLibraryDto Library { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("logging")]
  public SystemConfigLoggingDto Logging { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("machineLearning")]
  public SystemConfigMachineLearningDto MachineLearning { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("map")]
  public SystemConfigMapDto Map { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("metadata")]
  public SystemConfigMetadataDto Metadata { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("newVersionCheck")]
  public SystemConfigNewVersionCheckDto NewVersionCheck { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("nightlyTasks")]
  public SystemConfigNightlyTasksDto NightlyTasks { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("notifications")]
  public SystemConfigNotificationsDto Notifications { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("oauth")]
  public SystemConfigOAuthDto Oauth { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("passwordLogin")]
  public SystemConfigPasswordLoginDto PasswordLogin { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("reverseGeocoding")]
  public SystemConfigReverseGeocodingDto ReverseGeocoding { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("server")]
  public SystemConfigServerDto Server { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("storageTemplate")]
  public SystemConfigStorageTemplateDto StorageTemplate { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("templates")]
  public SystemConfigTemplatesDto Templates { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("theme")]
  public SystemConfigThemeDto Theme { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("trash")]
  public SystemConfigTrashDto Trash { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("user")]
  public SystemConfigUserDto User { get; set; } = null!;
}
