//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SystemConfigOAuthDto from OpenAPI schema.
/// Schema path: #/components/schemas/SystemConfigOAuthDto
/// </summary>
public class SystemConfigOAuthDto
{
  /// <summary>
  /// Auto launch
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("autoLaunch")]
  public bool AutoLaunch { get; set; }

  /// <summary>
  /// Auto register
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("autoRegister")]
  public bool AutoRegister { get; set; }

  /// <summary>
  /// Button text
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("buttonText")]
  public string? ButtonText { get; set; }

  /// <summary>
  /// Client ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("clientId")]
  public string? ClientId { get; set; }

  /// <summary>
  /// Client secret
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("clientSecret")]
  public string? ClientSecret { get; set; }

  /// <summary>
  /// Default storage quota
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("defaultStorageQuota")]
  public long? DefaultStorageQuota { get; set; }

  /// <summary>
  /// Enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool Enabled { get; set; }

  /// <summary>
  /// Issuer URL
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("issuerUrl")]
  public string? IssuerUrl { get; set; }

  /// <summary>
  /// Mobile override enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("mobileOverrideEnabled")]
  public bool MobileOverrideEnabled { get; set; }

  /// <summary>
  /// Mobile redirect URI
  /// </summary>
  [Required]
  [Url]
  [System.Text.Json.Serialization.JsonPropertyName("mobileRedirectUri")]
  public string? MobileRedirectUri { get; set; }

  /// <summary>
  /// Profile signing algorithm
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("profileSigningAlgorithm")]
  public string? ProfileSigningAlgorithm { get; set; }

  /// <summary>
  /// Role claim
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("roleClaim")]
  public string? RoleClaim { get; set; }

  /// <summary>
  /// Scope
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("scope")]
  public string? Scope { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("signingAlgorithm")]
  public string? SigningAlgorithm { get; set; }

  /// <summary>
  /// Storage label claim
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("storageLabelClaim")]
  public string? StorageLabelClaim { get; set; }

  /// <summary>
  /// Storage quota claim
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("storageQuotaClaim")]
  public string? StorageQuotaClaim { get; set; }

  /// <summary>
  /// Timeout
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("timeout")]
  public int Timeout { get; set; }

  /// <summary>
  /// Token endpoint auth method
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("tokenEndpointAuthMethod")]
  public OAuthTokenEndpointAuthMethod TokenEndpointAuthMethod { get; set; }
}
