//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SystemConfigJobDto from OpenAPI schema.
/// Schema path: #/components/schemas/SystemConfigJobDto
/// </summary>
public class SystemConfigJobDto
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("backgroundTask")]
  public JobSettingsDto BackgroundTask { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("editor")]
  public JobSettingsDto Editor { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("faceDetection")]
  public JobSettingsDto FaceDetection { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("library")]
  public JobSettingsDto Library { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("metadataExtraction")]
  public JobSettingsDto MetadataExtraction { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("migration")]
  public JobSettingsDto Migration { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("notifications")]
  public JobSettingsDto Notifications { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ocr")]
  public JobSettingsDto Ocr { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("search")]
  public JobSettingsDto Search { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("sidecar")]
  public JobSettingsDto Sidecar { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("smartSearch")]
  public JobSettingsDto SmartSearch { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("thumbnailGeneration")]
  public JobSettingsDto ThumbnailGeneration { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("videoConversion")]
  public JobSettingsDto VideoConversion { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("workflow")]
  public JobSettingsDto Workflow { get; set; } = null!;
}
