//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SystemConfigSmtpTransportDto from OpenAPI schema.
/// Schema path: #/components/schemas/SystemConfigSmtpTransportDto
/// </summary>
public class SystemConfigSmtpTransportDto
{
  /// <summary>
  /// SMTP server hostname
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("host")]
  public string? Host { get; set; }

  /// <summary>
  /// Whether to ignore SSL certificate errors
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ignoreCert")]
  public bool IgnoreCert { get; set; }

  /// <summary>
  /// SMTP password
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  /// <summary>
  /// SMTP server port
  /// </summary>
  [Required]
  [Range(0, 65535)]
  [System.Text.Json.Serialization.JsonPropertyName("port")]
  public decimal Port { get; set; }

  /// <summary>
  /// Whether to use secure connection (TLS/SSL)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("secure")]
  public bool Secure { get; set; }

  /// <summary>
  /// SMTP username
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("username")]
  public string? Username { get; set; }
}
