//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SystemConfigImageDto from OpenAPI schema.
/// Schema path: #/components/schemas/SystemConfigImageDto
/// </summary>
public class SystemConfigImageDto
{
  /// <summary>
  /// Colorspace
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("colorspace")]
  public Colorspace Colorspace { get; set; }

  /// <summary>
  /// Extract embedded
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("extractEmbedded")]
  public bool ExtractEmbedded { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("fullsize")]
  public SystemConfigGeneratedFullsizeImageDto Fullsize { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("preview")]
  public SystemConfigGeneratedImageDto Preview { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("thumbnail")]
  public SystemConfigGeneratedImageDto Thumbnail { get; set; } = null!;
}
