//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SystemConfigGeneratedFullsizeImageDto from OpenAPI schema.
/// Schema path: #/components/schemas/SystemConfigGeneratedFullsizeImageDto
/// </summary>
public class SystemConfigGeneratedFullsizeImageDto
{
  /// <summary>
  /// Enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool Enabled { get; set; }

  /// <summary>
  /// Image format
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("format")]
  public ImageFormat Format { get; set; }

  /// <summary>
  /// Progressive
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("progressive")]
  public bool? Progressive { get; set; }

  /// <summary>
  /// Quality
  /// </summary>
  [Required]
  [Range(1, 100)]
  [System.Text.Json.Serialization.JsonPropertyName("quality")]
  public int Quality { get; set; }
}
