//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SystemConfigTemplateStorageOptionDto from OpenAPI schema.
/// Schema path: #/components/schemas/SystemConfigTemplateStorageOptionDto
/// </summary>
public class SystemConfigTemplateStorageOptionDto
{
  /// <summary>
  /// Available day format options for storage template
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("dayOptions")]
  public List<string?>? DayOptions { get; set; }

  /// <summary>
  /// Available hour format options for storage template
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("hourOptions")]
  public List<string?>? HourOptions { get; set; }

  /// <summary>
  /// Available minute format options for storage template
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("minuteOptions")]
  public List<string?>? MinuteOptions { get; set; }

  /// <summary>
  /// Available month format options for storage template
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("monthOptions")]
  public List<string?>? MonthOptions { get; set; }

  /// <summary>
  /// Available preset template options
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("presetOptions")]
  public List<string?>? PresetOptions { get; set; }

  /// <summary>
  /// Available second format options for storage template
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("secondOptions")]
  public List<string?>? SecondOptions { get; set; }

  /// <summary>
  /// Available week format options for storage template
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("weekOptions")]
  public List<string?>? WeekOptions { get; set; }

  /// <summary>
  /// Available year format options for storage template
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("yearOptions")]
  public List<string?>? YearOptions { get; set; }
}
