//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SystemConfigNightlyTasksDto from OpenAPI schema.
/// Schema path: #/components/schemas/SystemConfigNightlyTasksDto
/// </summary>
public class SystemConfigNightlyTasksDto
{
  /// <summary>
  /// Cluster new faces
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("clusterNewFaces")]
  public bool ClusterNewFaces { get; set; }

  /// <summary>
  /// Database cleanup
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("databaseCleanup")]
  public bool DatabaseCleanup { get; set; }

  /// <summary>
  /// Generate memories
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("generateMemories")]
  public bool GenerateMemories { get; set; }

  /// <summary>
  /// Missing thumbnails
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("missingThumbnails")]
  public bool MissingThumbnails { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("startTime")]
  public string? StartTime { get; set; }

  /// <summary>
  /// Sync quota usage
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("syncQuotaUsage")]
  public bool SyncQuotaUsage { get; set; }
}
