//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SystemConfigFFmpegDto from OpenAPI schema.
/// Schema path: #/components/schemas/SystemConfigFFmpegDto
/// </summary>
public class SystemConfigFFmpegDto
{
  /// <summary>
  /// Transcode hardware acceleration
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("accel")]
  public TranscodeHWAccel Accel { get; set; }

  /// <summary>
  /// Accelerated decode
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("accelDecode")]
  public bool AccelDecode { get; set; }

  /// <summary>
  /// Accepted audio codecs
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("acceptedAudioCodecs")]
  public List<AudioCodec>? AcceptedAudioCodecs { get; set; }

  /// <summary>
  /// Accepted containers
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("acceptedContainers")]
  public List<VideoContainer>? AcceptedContainers { get; set; }

  /// <summary>
  /// Accepted video codecs
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("acceptedVideoCodecs")]
  public List<VideoCodec>? AcceptedVideoCodecs { get; set; }

  /// <summary>
  /// B-frames
  /// </summary>
  [Required]
  [Range(-1, 16)]
  [System.Text.Json.Serialization.JsonPropertyName("bframes")]
  public int Bframes { get; set; }

  /// <summary>
  /// CQ mode
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("cqMode")]
  public CQMode CqMode { get; set; }

  /// <summary>
  /// CRF
  /// </summary>
  [Required]
  [Range(0, 51)]
  [System.Text.Json.Serialization.JsonPropertyName("crf")]
  public int Crf { get; set; }

  /// <summary>
  /// GOP size
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("gopSize")]
  public int GopSize { get; set; }

  /// <summary>
  /// Max bitrate
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("maxBitrate")]
  public string? MaxBitrate { get; set; }

  /// <summary>
  /// Preferred hardware device
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("preferredHwDevice")]
  public string? PreferredHwDevice { get; set; }

  /// <summary>
  /// Preset
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("preset")]
  public string? Preset { get; set; }

  /// <summary>
  /// References
  /// </summary>
  [Required]
  [Range(0, 6)]
  [System.Text.Json.Serialization.JsonPropertyName("refs")]
  public int Refs { get; set; }

  /// <summary>
  /// Target audio codec
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("targetAudioCodec")]
  public AudioCodec TargetAudioCodec { get; set; }

  /// <summary>
  /// Target resolution
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("targetResolution")]
  public string? TargetResolution { get; set; }

  /// <summary>
  /// Target video codec
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("targetVideoCodec")]
  public VideoCodec TargetVideoCodec { get; set; }

  /// <summary>
  /// Temporal AQ
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("temporalAQ")]
  public bool TemporalAQ { get; set; }

  /// <summary>
  /// Threads
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("threads")]
  public int Threads { get; set; }

  /// <summary>
  /// Tone mapping
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("tonemap")]
  public ToneMapping Tonemap { get; set; }

  /// <summary>
  /// Transcode policy
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("transcode")]
  public TranscodePolicy Transcode { get; set; }

  /// <summary>
  /// Two pass
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("twoPass")]
  public bool TwoPass { get; set; }
}
