//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SystemConfigServerDto from OpenAPI schema.
/// Schema path: #/components/schemas/SystemConfigServerDto
/// </summary>
public class SystemConfigServerDto
{
  /// <summary>
  /// External domain
  /// </summary>
  [Required]
  [Url]
  [System.Text.Json.Serialization.JsonPropertyName("externalDomain")]
  public string? ExternalDomain { get; set; }

  /// <summary>
  /// Login page message
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("loginPageMessage")]
  public string? LoginPageMessage { get; set; }

  /// <summary>
  /// Public users
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("publicUsers")]
  public bool PublicUsers { get; set; }
}
