//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// SystemConfigMachineLearningDto from OpenAPI schema.
/// Schema path: #/components/schemas/SystemConfigMachineLearningDto
/// </summary>
public class SystemConfigMachineLearningDto
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("availabilityChecks")]
  public MachineLearningAvailabilityChecksDto AvailabilityChecks { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("clip")]
  public ClipConfig Clip { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("duplicateDetection")]
  public DuplicateDetectionConfig DuplicateDetection { get; set; } = null!;

  /// <summary>
  /// Enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool Enabled { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("facialRecognition")]
  public FacialRecognitionConfig FacialRecognition { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ocr")]
  public OcrConfig Ocr { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("urls")]
  public List<string?>? Urls { get; set; }
}
