//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// TagBulkAssetsDto from OpenAPI schema.
/// Schema path: #/components/schemas/TagBulkAssetsDto
/// </summary>
public class TagBulkAssetsDto
{
  /// <summary>
  /// Asset IDs
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assetIds")]
  public List<Guid>? AssetIds { get; set; }

  /// <summary>
  /// Tag IDs
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("tagIds")]
  public List<Guid>? TagIds { get; set; }
}
