//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// TagCreateDto from OpenAPI schema.
/// Schema path: #/components/schemas/TagCreateDto
/// </summary>
public class TagCreateDto
{
  /// <summary>
  /// Tag color (hex)
  /// </summary>
  [RegularExpression(@"^#?([0-9A-F]{3}|[0-9A-F]{4}|[0-9A-F]{6}|[0-9A-F]{8})$")]
  [System.Text.Json.Serialization.JsonPropertyName("color")]
  public string? Color { get; set; }

  /// <summary>
  /// Tag name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// Parent tag ID
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("parentId")]
  public Guid? ParentId { get; set; }
}
