//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// TagResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/TagResponseDto
/// </summary>
public class TagResponseDto
{
  /// <summary>
  /// Tag color (hex)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("color")]
  public string? Color { get; set; }

  /// <summary>
  /// Creation date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public DateTime CreatedAt { get; set; }

  /// <summary>
  /// Tag ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Tag name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// Parent tag ID
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("parentId")]
  public string? ParentId { get; set; }

  /// <summary>
  /// Last update date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
  public DateTime UpdatedAt { get; set; }

  /// <summary>
  /// Tag value (full path)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("value")]
  public string? Value { get; set; }
}
