//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// TagsResponse from OpenAPI schema.
/// Schema path: #/components/schemas/TagsResponse
/// </summary>
public class TagsResponse
{
  /// <summary>
  /// Whether tags are enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool Enabled { get; set; }

  /// <summary>
  /// Whether tags appear in web sidebar
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("sidebarWeb")]
  public bool SidebarWeb { get; set; }
}
