//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// TemplateDto from OpenAPI schema.
/// Schema path: #/components/schemas/TemplateDto
/// </summary>
public class TemplateDto
{
  /// <summary>
  /// Template name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("template")]
  public string? Template { get; set; }
}
