//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// TimeBucketsResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/TimeBucketsResponseDto
/// </summary>
public class TimeBucketsResponseDto
{
  /// <summary>
  /// Number of assets in this time bucket
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("count")]
  public int Count { get; set; }

  /// <summary>
  /// Time bucket identifier in YYYY-MM-DD format representing the start of the time period
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("timeBucket")]
  public string? TimeBucket { get; set; }
}
