//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// TimeBucketAssetResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/TimeBucketAssetResponseDto
/// </summary>
public class TimeBucketAssetResponseDto
{
  /// <summary>
  /// Array of city names extracted from EXIF GPS data
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("city")]
  public List<string?>? City { get; set; }

  /// <summary>
  /// Array of country names extracted from EXIF GPS data
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("country")]
  public List<string?>? Country { get; set; }

  /// <summary>
  /// Array of video durations in HH:MM:SS format (null for images)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("duration")]
  public List<string?>? Duration { get; set; }

  /// <summary>
  /// Array of file creation timestamps in UTC
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("fileCreatedAt")]
  public List<string?>? FileCreatedAt { get; set; }

  /// <summary>
  /// Array of asset IDs in the time bucket
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public List<string?>? Id { get; set; }

  /// <summary>
  /// Array indicating whether each asset is favorited
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isFavorite")]
  public List<bool>? IsFavorite { get; set; }

  /// <summary>
  /// Array indicating whether each asset is an image (false for videos)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isImage")]
  public List<bool>? IsImage { get; set; }

  /// <summary>
  /// Array indicating whether each asset is in the trash
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isTrashed")]
  public List<bool>? IsTrashed { get; set; }

  /// <summary>
  /// Array of latitude coordinates extracted from EXIF GPS data
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("latitude")]
  public List<decimal?>? Latitude { get; set; }

  /// <summary>
  /// Array of live photo video asset IDs (null for non-live photos)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("livePhotoVideoId")]
  public List<string?>? LivePhotoVideoId { get; set; }

  /// <summary>
  /// Array of UTC offset hours at the time each photo was taken. Positive values are east of UTC, negative values are west of UTC. Values may be fractional (e.g., 5.5 for +05:30, -9.75 for -09:45). Applying this offset to &apos;fileCreatedAt&apos; will give you the time the photo was taken from the photographer&apos;s perspective.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("localOffsetHours")]
  public List<decimal>? LocalOffsetHours { get; set; }

  /// <summary>
  /// Array of longitude coordinates extracted from EXIF GPS data
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("longitude")]
  public List<decimal?>? Longitude { get; set; }

  /// <summary>
  /// Array of owner IDs for each asset
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ownerId")]
  public List<string?>? OwnerId { get; set; }

  /// <summary>
  /// Array of projection types for 360° content (e.g., &quot;EQUIRECTANGULAR&quot;, &quot;CUBEFACE&quot;, &quot;CYLINDRICAL&quot;)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("projectionType")]
  public List<string?>? ProjectionType { get; set; }

  /// <summary>
  /// Array of aspect ratios (width/height) for each asset
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ratio")]
  public List<decimal>? Ratio { get; set; }

  /// <summary>
  /// Array of stack information as [stackId, assetCount] tuples (null for non-stacked assets)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("stack")]
  public List<List<string?>?>? Stack { get; set; }

  /// <summary>
  /// Array of BlurHash strings for generating asset previews (base64 encoded)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("thumbhash")]
  public List<string?>? Thumbhash { get; set; }

  /// <summary>
  /// Array of visibility statuses for each asset (e.g., ARCHIVE, TIMELINE, HIDDEN, LOCKED)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("visibility")]
  public List<AssetVisibility>? Visibility { get; set; }
}
