//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// UpdateConfigRequest from OpenAPI schema.
/// Schema path: #/components/schemas/UpdateConfigRequest
/// </summary>
public class UpdateConfigRequest
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("backup")]
  public required SystemConfigBackupsDto Backup { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ffmpeg")]
  public required SystemConfigFFmpegDto Ffmpeg { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("image")]
  public required SystemConfigImageDto Image { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("job")]
  public required SystemConfigJobDto Job { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("library")]
  public required SystemConfigLibraryDto Library { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("logging")]
  public required SystemConfigLoggingDto Logging { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("machineLearning")]
  public required SystemConfigMachineLearningDto MachineLearning { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("map")]
  public required SystemConfigMapDto Map { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("metadata")]
  public required SystemConfigMetadataDto Metadata { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("newVersionCheck")]
  public required SystemConfigNewVersionCheckDto NewVersionCheck { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("nightlyTasks")]
  public required SystemConfigNightlyTasksDto NightlyTasks { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("notifications")]
  public required SystemConfigNotificationsDto Notifications { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("oauth")]
  public required SystemConfigOAuthDto Oauth { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("passwordLogin")]
  public required SystemConfigPasswordLoginDto PasswordLogin { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("reverseGeocoding")]
  public required SystemConfigReverseGeocodingDto ReverseGeocoding { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("server")]
  public required SystemConfigServerDto Server { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("storageTemplate")]
  public required SystemConfigStorageTemplateDto StorageTemplate { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("templates")]
  public required SystemConfigTemplatesDto Templates { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("theme")]
  public required SystemConfigThemeDto Theme { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("trash")]
  public required SystemConfigTrashDto Trash { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("user")]
  public required SystemConfigUserDto User { get; set; }
}
