//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// UpdateAssetDto from OpenAPI schema.
/// Schema path: #/components/schemas/UpdateAssetDto
/// </summary>
public class UpdateAssetDto
{
  /// <summary>
  /// Original date and time
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("dateTimeOriginal")]
  public string? DateTimeOriginal { get; set; }

  /// <summary>
  /// Asset description
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Mark as favorite
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isFavorite")]
  public bool? IsFavorite { get; set; }

  /// <summary>
  /// Latitude coordinate
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("latitude")]
  public decimal? Latitude { get; set; }

  /// <summary>
  /// Live photo video ID
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("livePhotoVideoId")]
  public Guid? LivePhotoVideoId { get; set; }

  /// <summary>
  /// Longitude coordinate
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("longitude")]
  public decimal? Longitude { get; set; }

  /// <summary>
  /// Rating in range [1-5], or null for unrated
  /// </summary>
  [Range(-1, 5)]
  [System.Text.Json.Serialization.JsonPropertyName("rating")]
  public decimal? Rating { get; set; }

  /// <summary>
  /// Asset visibility
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("visibility")]
  public AssetVisibility? Visibility { get; set; }
}
