//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// UsageByUserDto from OpenAPI schema.
/// Schema path: #/components/schemas/UsageByUserDto
/// </summary>
public class UsageByUserDto
{
  /// <summary>
  /// Number of photos
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("photos")]
  public int Photos { get; set; }

  /// <summary>
  /// User quota size in bytes (null if unlimited)
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("quotaSizeInBytes")]
  public long? QuotaSizeInBytes { get; set; }

  /// <summary>
  /// Total storage usage in bytes
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("usage")]
  public long Usage { get; set; }

  /// <summary>
  /// Storage usage for photos in bytes
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("usagePhotos")]
  public long UsagePhotos { get; set; }

  /// <summary>
  /// Storage usage for videos in bytes
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("usageVideos")]
  public long UsageVideos { get; set; }

  /// <summary>
  /// User ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("userId")]
  public string? UserId { get; set; }

  /// <summary>
  /// User name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("userName")]
  public string? UserName { get; set; }

  /// <summary>
  /// Number of videos
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("videos")]
  public int Videos { get; set; }
}
