//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// UserPreferencesResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/UserPreferencesResponseDto
/// </summary>
public class UserPreferencesResponseDto
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("albums")]
  public AlbumsResponse Albums { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("cast")]
  public CastResponse Cast { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("download")]
  public DownloadResponse Download { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("emailNotifications")]
  public EmailNotificationsResponse EmailNotifications { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("folders")]
  public FoldersResponse Folders { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("memories")]
  public MemoriesResponse Memories { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("people")]
  public PeopleResponse People { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("purchase")]
  public PurchaseResponse Purchase { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ratings")]
  public RatingsResponse Ratings { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("sharedLinks")]
  public SharedLinksResponse SharedLinks { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("tags")]
  public TagsResponse Tags { get; set; } = null!;
}
