//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// UserAdminUpdateDto from OpenAPI schema.
/// Schema path: #/components/schemas/UserAdminUpdateDto
/// </summary>
public class UserAdminUpdateDto
{
  /// <summary>
  /// Avatar color
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("avatarColor")]
  public UserAvatarColor? AvatarColor { get; set; }

  /// <summary>
  /// User email
  /// </summary>
  [EmailAddress]
  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  /// <summary>
  /// Grant admin privileges
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isAdmin")]
  public bool? IsAdmin { get; set; }

  /// <summary>
  /// User name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// User password
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  /// <summary>
  /// PIN code
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("pinCode")]
  public string? PinCode { get; set; }

  /// <summary>
  /// Storage quota in bytes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("quotaSizeInBytes")]
  public long? QuotaSizeInBytes { get; set; }

  /// <summary>
  /// Require password change on next login
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("shouldChangePassword")]
  public bool? ShouldChangePassword { get; set; }

  /// <summary>
  /// Storage label
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("storageLabel")]
  public string? StorageLabel { get; set; }
}
