//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// UserAdminResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/UserAdminResponseDto
/// </summary>
public class UserAdminResponseDto
{
  /// <summary>
  /// Avatar color
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("avatarColor")]
  public UserAvatarColor AvatarColor { get; set; }

  /// <summary>
  /// Creation date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public DateTime CreatedAt { get; set; }

  /// <summary>
  /// Deletion date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("deletedAt")]
  public DateTime? DeletedAt { get; set; }

  /// <summary>
  /// User email
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  /// <summary>
  /// User ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Is admin user
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isAdmin")]
  public bool IsAdmin { get; set; }

  /// <summary>
  /// User license
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("license")]
  public UserLicense License { get; set; } = null!;

  /// <summary>
  /// User name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// OAuth ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("oauthId")]
  public string? OauthId { get; set; }

  /// <summary>
  /// Profile change date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("profileChangedAt")]
  public DateTime ProfileChangedAt { get; set; }

  /// <summary>
  /// Profile image path
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("profileImagePath")]
  public string? ProfileImagePath { get; set; }

  /// <summary>
  /// Storage quota in bytes
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("quotaSizeInBytes")]
  public long? QuotaSizeInBytes { get; set; }

  /// <summary>
  /// Storage usage in bytes
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("quotaUsageInBytes")]
  public long? QuotaUsageInBytes { get; set; }

  /// <summary>
  /// Require password change on next login
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("shouldChangePassword")]
  public bool ShouldChangePassword { get; set; }

  /// <summary>
  /// User status
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public UserStatus Status { get; set; }

  /// <summary>
  /// Storage label
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("storageLabel")]
  public string? StorageLabel { get; set; }

  /// <summary>
  /// Last update date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
  public DateTime UpdatedAt { get; set; }
}
