//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// ValidateLibraryResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/ValidateLibraryResponseDto
/// </summary>
public class ValidateLibraryResponseDto
{
  /// <summary>
  /// Validation results for import paths
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("importPaths")]
  public List<ValidateLibraryImportPathResponseDto>? ImportPaths { get; set; }
}
