//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// ValidateLibraryImportPathResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/ValidateLibraryImportPathResponseDto
/// </summary>
public class ValidateLibraryImportPathResponseDto
{
  /// <summary>
  /// Import path
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("importPath")]
  public string? ImportPath { get; set; }

  /// <summary>
  /// Is valid
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isValid")]
  public bool IsValid { get; set; }

  /// <summary>
  /// Validation message
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("message")]
  public string? Message { get; set; }
}
