//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// WorkflowResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/WorkflowResponseDto
/// </summary>
public class WorkflowResponseDto
{
  /// <summary>
  /// Workflow actions
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("actions")]
  public List<WorkflowActionResponseDto>? Actions { get; set; }

  /// <summary>
  /// Creation date
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public string? CreatedAt { get; set; }

  /// <summary>
  /// Workflow description
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Workflow enabled
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool Enabled { get; set; }

  /// <summary>
  /// Workflow filters
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("filters")]
  public List<WorkflowFilterResponseDto>? Filters { get; set; }

  /// <summary>
  /// Workflow ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Workflow name
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// Owner user ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ownerId")]
  public string? OwnerId { get; set; }

  /// <summary>
  /// Workflow trigger type
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("triggerType")]
  public PluginTriggerType TriggerType { get; set; }
}
