//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// WorkflowFilterResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/WorkflowFilterResponseDto
/// </summary>
public class WorkflowFilterResponseDto
{
  /// <summary>
  /// Filter configuration
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("filterConfig")]
  public object? FilterConfig { get; set; }

  /// <summary>
  /// Filter ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Filter order
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("order")]
  public decimal Order { get; set; }

  /// <summary>
  /// Plugin filter ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("pluginFilterId")]
  public string? PluginFilterId { get; set; }

  /// <summary>
  /// Workflow ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("workflowId")]
  public string? WorkflowId { get; set; }
}
