//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// WorkflowUpdateDto from OpenAPI schema.
/// Schema path: #/components/schemas/WorkflowUpdateDto
/// </summary>
public class WorkflowUpdateDto
{
  /// <summary>
  /// Workflow actions
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("actions")]
  public List<WorkflowActionItemDto>? Actions { get; set; }

  /// <summary>
  /// Workflow description
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Workflow enabled
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool? Enabled { get; set; }

  /// <summary>
  /// Workflow filters
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("filters")]
  public List<WorkflowFilterItemDto>? Filters { get; set; }

  /// <summary>
  /// Workflow name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// Workflow trigger type
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("triggerType")]
  public PluginTriggerType? TriggerType { get; set; }
}
