//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// WorkflowActionItemDto from OpenAPI schema.
/// Schema path: #/components/schemas/WorkflowActionItemDto
/// </summary>
public class WorkflowActionItemDto
{
  /// <summary>
  /// Action configuration
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("actionConfig")]
  public object? ActionConfig { get; set; }

  /// <summary>
  /// Plugin action ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("pluginActionId")]
  public Guid PluginActionId { get; set; }
}
