//
// <auto-generated>
// Immich API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/immich.json
// API: Immich
// Version: 2.6.2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Immich.Models;

/// <summary>
/// WorkflowActionResponseDto from OpenAPI schema.
/// Schema path: #/components/schemas/WorkflowActionResponseDto
/// </summary>
public class WorkflowActionResponseDto
{
  /// <summary>
  /// Action configuration
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("actionConfig")]
  public object? ActionConfig { get; set; }

  /// <summary>
  /// Action ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// Action order
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("order")]
  public decimal Order { get; set; }

  /// <summary>
  /// Plugin action ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("pluginActionId")]
  public string? PluginActionId { get; set; }

  /// <summary>
  /// Workflow ID
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("workflowId")]
  public string? WorkflowId { get; set; }
}
